### ISSUE TITLE
Readme missing supported language

### ISSUE THREAD

**Issue by tlannigan** [engineer-man/piston#123]
JavaScript is used as the language argument under **Execute Endpoint**, but it is not listed under supported languages.

**Comment by realtux** [comment]
`javascript` is technically an alias of the executor `node`, see here: https://github.com/engineer-man/piston/blob/master/config/languages.json#L146

**Comment by ThreshMain** [comment]
> `javascript` is technically an alias of the executor `node`, see here: https://github.com/engineer-man/piston/blob/master/config/languages.json#L146

Well, that's true but isn't node/node.js just an interpreter and the language is javascript? So shouldn't it be the other way around and having JavaScript in the supported language list and node.js/node as an alias to keep it the same for all languages?

**Comment by realtux** [comment]
the thing is that `node` will always be `javascript`, but `javascript` will not always be `node`, so it makes sense for the runtime to be the executor.
