### ISSUE TITLE
C# (.NET 5) executor

### ISSUE THREAD

**Issue by Gabriel-Paulucci** [engineer-man/piston#127]
You currently have the C # version in Mono, and I would like it to be possible to upgrade to the .NET 5 version which is multiplatform and contains new features

**Comment by HexF** [comment]
I put this on the v3 roadmap, because this is very achievable for us in v3 compared to the old version.
Are you willing to build this yourself, or would you prefer if someone else builds it?

**Comment by Gabriel-Paulucci** [comment]
Yes i could try to do

**Comment by Gabriel-Paulucci** [comment]
I'm not able to run the container

**Comment by HexF** [comment]
Hop into the discord and we will help you out.
https://discord.gg/engineerman
#emkc-felix-piston

**Comment by HexF** [comment]
cbe759ab5667e91ecbdd5f3a2b92e1663e3ae6df
