### ISSUE TITLE
Dart

### ISSUE THREAD

**Issue by psrcek** [engineer-man/piston#132]
Please add dart support. Should be quite easy.

**Comment by Vrganj** [comment]
https://dart.dev/tools/sdk/archive
x64, zip

Not sure whether to pr to the main branch or v3

**Comment by realtux** [comment]
main

**Comment by HexF** [comment]
Merge it into v3

**Comment by HexF** [comment]
39adb13ba1910e440ad9beb2ba95e1f6f0bb06c5
