### ISSUE TITLE
Python modules

### ISSUE THREAD

**Issue by ThreshMain** [engineer-man/piston#133]
Few pacakges ideas that would be nice to have available
- [ ] numpy
- [ ] scipy
- [ ] pandas
- [ ] pycrypto
- [ ] numba
- [ ] whoosh
- [ ] bcrypt
- [ ] passlib

**Comment by HexF** [comment]
Should be easy enough - do it in a similar way to how Jelly is installed, but within python and it should in theory work :tm:

**Comment by HexF** [comment]
numba simply cant be installed as it depends on llvm being installed in the container

**Comment by HexF** [comment]
All packages added except numba, and panda in py2 as it seems to dislike it

**Comment by dabadabadoue** [comment]
This doesn't seem to work with the discord bot, or maybe I'm just using it incorrectly. Just trying to use numpy but keeps saying that there is no module named numpy. Any help would be appreciated

**Comment by HexF** [comment]
The public instance isn't currently running v3, it should be working in the next week or 2.

**Comment by StathisKap** [comment]
what's the best way to install pytorch in python 3.11.0?
I extended the build.sh and built it using ./piston build-pkg but then I'd like to deploy it on kubernetes and I don't see an easy way of getting pytorch on there.
Maybe using dind and logging into the container and setting it up that way

**Comment by timiil** [comment]
maybe we can make a conda env, and then put it to run the code , that will be very NICE?

**Comment by jackrankin** [comment]
@StathisKap did you ever find a good way of doing this? I've only managed to get some bloated docker images (3gb ish) with pytorch preinstalled
