### ISSUE TITLE
run Website

### ISSUE THREAD

**Issue by luis605** [engineer-man/piston#134]
Hello, I have a python code, but is very big to I put on discord, so I use pastebin. i thing we can run pastebin.com code

**Comment by Vrganj** [comment]
There was an online editor being worked on. Not sure what the progress is. In the meantime, you can use the API if you know how.

**Comment by ccall48** [comment]
Yes you can pass it pastebin code to run, if you know how to pass it to the API it works.

**Comment by luis605** [comment]
oh ok thank you
