### ISSUE TITLE
Add MySQL / Postgres

### ISSUE THREAD

**Issue by leoseccia** [engineer-man/piston#135]
I would love to be able to run SQL :-)

What you have done is awesome...

**Comment by Vrganj** [comment]
And how do you propose that would work? A database running on the server?

**Comment by realtux** [comment]
this would probably need to be implemented as a static database with a variety of junk data and a user without delete permissions, from there the executor is really not any different from the rest of them

**Comment by Vrganj** [comment]
SQLite would be pretty simple to implement, not sure about others.

**Comment by handlederror** [comment]
> And how do you propose that would work? A database running on the server?

@Vrganj Or a database running on different server?

**Comment by leoseccia** [comment]
The way I was thinking was to provision the image with a temporary db already created, and just allow for `CREATE TABLE`, `DROP TABLE`, `INSERT`, `SELECT` and `DELETE`...

**Comment by leoseccia** [comment]
There are other (non-esoteric) languages I would love to see :-p

F#, R, Clojure and CoffeeScript... If I get round to it I will PR them, unless someone beats me to it :-)

**Comment by HexF** [comment]
Cleaning up old stale issues, and this seems out of scope for what piston does.
