### ISSUE TITLE
Batch submissions with different stdin

### ISSUE THREAD

**Issue by ragrag** [engineer-man/piston#169]
## Proposal
I propose adding the possibility for running code more than once with different stdin

I suppose the interface for such a thing can be something like this
```
POST /execute/batch
```
```js
[
  {
    "language": "python",
    "source": "print(input())",
    "stdin":[
       "Hello",
       "World!"
      ]
  }
]
```
and similarly the response:
```js
[
  {
    "ran": true,
    "language": "python",
    "version": "3.8",
    "output": "Hello",
    "stdout": "Hello",
    "stderr": ""
  },
  {
    "ran": true,
    "language": "python",
    "version": "3.8",
    "output": "World!",
    "stdout": "World!",
    "stderr": ""
  }
]
```
I think an extra api param can be provided to stop execution on the first killed process or this can be the default behavior.

## Motivation
I believe this has lots of applications but most notably when using Piston in code judging/evaluation (when there are multiple test cases with certain expected outputs, which can frankly be a separate issue/feature request of its own)

I believe this can be more resource efficient because:
- To do this behavior currently we can send multiple execution requests each for a single stdin/input but I believe having them all in a single request can be much more resource efficient especially with compiled languages, since the code will be only compiled once and then ran with the different stdins instead of being compiled separately with each request/stdin
-  Can save up on the number of requests handled by the api since a single request will replace multiple requests

## Limitations
I believe there can be some limitations to that for the public API such as having a cap on the number of stdins/inputs or requests/second . However I believe for self-hosted instances of Piston this can be a very beneficial feature.

**Comment by HexF** [comment]
We have had this come up before - it's not something we would implement in the core api.

**Comment by ragrag** [comment]
Thank you for the clarification and for the great project and I can't wait for v3!, guess I will have to hack it for my own use case.
