### ISSUE TITLE
Update bash

### ISSUE THREAD

**Issue by MonliH** [engineer-man/piston#17]
You should update bash, the current one is ~4 years old.

**Comment by mllegoman** [comment]
I would think having something 4 years old would help. 
It has more support.
It's easy to maintain.
And you can find random compilers for bash online that are 4.4.20. Makes coding cross-platform easier.

**Comment by Vrganj** [comment]
It isn't 4 (maybe even 5 now) years old on purpose, it's just that it wasn't installed manually. The public Piston instance just uses the Bash version the LXC container came with.

**Comment by realtux** [comment]
im going to need to bump the ubuntu base image version soon anyway and this might come with a newer bash version, but even if it doesn't i think that's ok
