### ISSUE TITLE
PHP For Loop Variable Increment Bug

### ISSUE THREAD

**Issue by TimAnthonyAlexander** [engineer-man/piston#179]
Running the following test code over the API:

```
<?php

$myArray = ["My", "Pretty", "Array"];

for($x = 0; $x < count($myArray); $x++){
  echo $myArray[$x];
}
```

should result in this:

```
MyPrettyArray
```

but instead results in this:

```
MyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMyMy [...]
```

---

Now, I don't know what the issue is exactly... It seems $x does not increment as it should. Very weird. If I write a "manual" for-loop it still does the same thing. When I do not `echo $myArray[$x];` it just says "Killed", so apparently the Code execution gets cut off after a certain amount of time.
I used POST to send the code via PHP cURL to the API.
Running the same code in any other service (or locally in a php server) results in the correct, wanted result.
And this behaviour has only appeared for me with this example.

---

I'd be happy to be corrected if the problem lies on my end.

**Comment by realtux** [comment]
im not sure, I just tried it and it worked as expected. are you positive you are sending that exact code? can you supply the exact php code you used to send the above code to the piston api?

![Screenshot_20210319-033600](https://user-images.githubusercontent.com/4989650/111753143-80909c00-8864-11eb-97da-a2126b11d031.jpg)

**Comment by TimAnthonyAlexander** [comment]
Okay, here is the exact code:

```
    public function calculate(){
        $data = $this->data;
        $language = $this->language;
        $return = json_decode($this->apicall("https://emkc.org/api/v1/piston/execute", "source=$data&language=$language"), true);
        $this->return = $return;
        return $return["output"];
    }

    private function apicall($url, $postvars){
        $ch = curl_init();
        $config['useragent'] = 'dev@myocto.de';
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postvars);
        curl_setopt($ch, CURLOPT_FAILONERROR, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
        $retValue = (string)curl_exec($ch);
        curl_close($ch);
        return $retValue;
    }
```

Setting the $data variable to 
```
<?php

$myArray = ["My", "Pretty", "Array"];

$x = (int)0;

while($x < count($myArray)){
  $x = $x++;
  echo $myArray[$x];
}
```

via POST. $language variable obviously has no relevance here, since that works.

**Comment by TimAnthonyAlexander** [comment]
Maybe I can setup a test API that outputs what exactly is received via this code to see if the code is exactly what I am trying to send. It seems some part of the `$x` variable part seems not to be what it should be. Not sure though.

**Comment by realtux** [comment]
the code you supplied the first time doesn't match the code you supplied just now. this code does indeed result in an infinite loop. $x = $x++ doesn't do what you think it does. it returns the value of x, increments the original value of x, then assigns the original value back to x. you're basically doing $x = $x.

change $x = $x++ to $x++

**Comment by TimAnthonyAlexander** [comment]
Well I did setup a test API that shows me what it receives on that exact cURL Call:

```
<?php


$myArray = ["My", "Pretty", "Array"];



for($x = 0; $x < count($myArray); $x  ){

  echo $myArray[$x];

}
```

Very weird. The ++ gets lost. Might be cURL then?

**Comment by TimAnthonyAlexander** [comment]
> the code you supplied the first time doesn't match the code you supplied just now. this code does indeed result in an infinite loop. $x = $x++ doesn't do what you think it does. it returns the value of x, increments the original value of x, then assigns the original value back to x. you're basically doing $x = $x.
> 
> change $x = $x++ to $x++

Well I inserted the wrong code here. The first code is what was actually run.

**Comment by realtux** [comment]
you need to send it as json. + has a special meaning in url encoded parameters

**Comment by TimAnthonyAlexander** [comment]
That seems to be the issue. Thank you for resolving it.

**Comment by realtux** [comment]
no problem, good luck
