### ISSUE TITLE
v3: Following the Just Piston (no CLI) instructions results in a container with no runtimes 

### ISSUE THREAD

**Issue by leoseccia** [engineer-man/piston#183]
Hello,

Kudos to all of you for creating such a cool project. @HexF nice and clear update to the v3 instructions. Thank you. 

I just followed the **_Just Piston (no CLI)_** instructions on the **_v3_** branch and the container fires up but when I perform a GET to http://localhost:6969/runtimes - no runtimes are returned ie. `[ ]`.

**Comment by leoseccia** [comment]
I just tried the other instructions and I get a similar result... Here is the error:

```
> cli/index.js -u http://127.0.0.1:6969 ppman list
piston ppman list

Lists all available packages

Options:
      --version     Show version number                        [boolean]
  -u, --piston-url  Piston API URL
                             [string] [default: "http://127.0.0.1:6969"]
      --help        Show help                                  [boolean]

Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  config: {
    url: '/packages',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    baseURL: 'http://127.0.0.1:6969',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/packages',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '127.0.0.1',
      port: '6969',
      nativeProtocols: [Object],
      pathname: '/packages'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /packages HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: 127.0.0.1:6969\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/packages',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://127.0.0.1:6969/packages',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by HexF** [comment]
You need to install some packages first using the command line. Just piston is there for people who want to use their own tooling with it, therefore I recommend you use the all in one distribution.

**Comment by HexF** [comment]
Can you post some logs from your api container from the crash, that will help me fix that

**Comment by leoseccia** [comment]
Hello @HexF , thanks for looking into it. Attached is the log file. I just did `docker container logs piston_piston_api_1 > piston_api.log`, please let me know if you would like me to run something else.

The host is a Mac but got similar issues with Win/WSL2.

[piston_api.log](https://github.com/engineer-man/piston/files/6176654/piston_api.log)

**Comment by HexF** [comment]
What command did you use to start the container? It looks like the CLI can't contact the piston api.

**Comment by leoseccia** [comment]
i just used the one from the instructions i.e. `docker-compose up -d piston_api`.

**Comment by HexF** [comment]
I think WSL and MacOS might do something funny with opening ports on docker and not forwarding them to localhost correctly. The API never gets contacted form the logs, so I think that is the issue.
Can you try this on something running Linux and see if that works?

**Comment by leoseccia** [comment]
@HexF - In Ubuntu, it just works...

**Comment by leoseccia** [comment]
To add some details about the issue on MacOS:

- `http://localhost:6969/` returns a 404 => expected
- `http://localhost:6969/runtimes` returns a 200 with `[]` => also expected
- `http://localhost:6969/packages` does not return a HTTP response, it just says `Error: socket hang up`

**Comment by HexF** [comment]
That means for some reason the container can't access the Internet, any way you can test this?

**Comment by leoseccia** [comment]
Ok, in order to `ping`, I had to change the base image to `node:current-buster`. 

Here is the result. Internet access seems fine.

```
docker run --rm piston_piston_api ping -c 2 www.google.com
PING www.google.com (216.58.205.36) 56(84) bytes of data.
64 bytes from lhr48s23-in-f4.1e100.net (216.58.205.36): icmp_seq=1 ttl=37 time=16.1 ms
64 bytes from lhr48s23-in-f4.1e100.net (216.58.205.36): icmp_seq=2 ttl=37 time=20.5 ms

--- www.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 5ms
rtt min/avg/max/mdev = 16.132/18.339/20.546/2.207 ms
```

**Comment by leoseccia** [comment]
Every time I hit `/packages` the container restarts instantly. I am starting to wonder whether it is a file system linking issue.

**Comment by HexF** [comment]
The issue would be it can't parse the index file and crashes. Can you upload your `config.yaml` file, which should be somewhere in the `data` dir?

**Comment by leoseccia** [comment]
Hello Thomas, the `data/piston/config.yaml` is the one I pulled from the repo - no diffs.

**Comment by leoseccia** [comment]
Interestingly doing `curl http://localhost:6969/packages` from inside the container also kills it (and I get kicked out... last message being: `curl: (52) Empty reply from server`)

**Comment by leoseccia** [comment]
I think I might have found the issue: 
![image](https://user-images.githubusercontent.com/2159624/112229305-a635f080-8c2a-11eb-9413-a1e8edd14e6f.png)

**Comment by leoseccia** [comment]
So this fixes it:
![image](https://user-images.githubusercontent.com/2159624/112231501-bcde4680-8c2e-11eb-880c-40dbb06c0b97.png)

However we probably want to find a way to actually use fetch. Suggestions?

**Comment by leoseccia** [comment]
could be related to this: https://github.com/node-fetch/node-fetch/issues/375

**Comment by HexF** [comment]
Can you give this another test, I dont think hard-coding in the repo content should be required.

**Comment by leoseccia** [comment]
Hello @HexF, I sort of given up on this issue because I don't really use the Mac anymore. However, I fired it up just now, I cleaned docker and started from scratch. 

Unfortunately, the container does not start anymore, and I get `[ERROR] config: Config key disable_networking does not exist on currently loaded configuration`.

I don't have time to look into it today, but I will try to get back to it at some point soon. Let me know if you would like me to try something in particular.

**Comment by dvargas46** [comment]
Hi @leoseccia . I ran into this issue the other day as well. It is because we added a new way for disabling networking within the container without requiring a privileged container, thus improving its overall security.

Try deleting the `data/piston/config.yaml` config file and spin up the container again. The file will be recreated with the proper config key/values.

**Comment by leoseccia** [comment]
...and it works! Thank you @HexF + @dvargas46
