### ISSUE TITLE
Nix language

### ISSUE THREAD

**Issue by MagicRB** [engineer-man/piston#190]
It'd be really cool if piston could execute Nix scripts, issue is that for Nix to work without recompiling everything, it needs read write access to `/nix`. If we got that, there are then two modes of operating Nix, there is single-user mode, where `/nix` is owned by the main user and daemon mode, where a `nix`binary runs in the background as a daemon. By looking at the existing v3 packages, I think there is no support for creating `/nix`, there is no way to get around that requirement so if you don't want add `/nix` you can close this immediately, (also, we would need to garbage collect /nix periodically since Nix doesn't delete things automatically). Thanks for reading :)

**Comment by HexF** [comment]
Issue would be that with nix you can build and keep files persistently on disk, that is if they are cached in `/nix`

**Comment by HexF** [comment]
cleaning stale issues, and seems Nix seems to be out of scope.
