### ISSUE TITLE
Add all valid file types for each language to its aliases 

### ISSUE THREAD

**Issue by brtwrst** [engineer-man/piston#197]
I have enabled piston-bot to take attached files instead of a codeblock and if the user does not specify a language it will use the file extension as language.

Therefore every supported language should include all valid filename extensions for that language in its aliases when calling the [versions](https://emkc.org/api/v1/piston/versions) endpoint.

Please make sure this is the case for all existing languages.

**Comment by HexF** [comment]
This is reassured in testing, test scripts must end in an alias for the specific package, e.g. `test.py` will use `py` as the language to query with.
