### ISSUE TITLE
Common Lisp should not be called "clisp"

### ISSUE THREAD

**Issue by mfiano** [engineer-man/piston#199]
https://github.com/engineer-man/piston/blob/16c585d41d649af8a1be4cd35559d60970f27339/config/languages.json#L61

Common Lisp is an ANSI standard for implementing the language also called Common Lisp. CLISP is only but one such slow, out-dated implementation of this language that hasn't made a release in over 10 years.

It is a common newcomer mistake to refer to Common Lisp the language, or Common Lisp the ANSI standard, as "CLISP" or "clisp". CLISP is but one implementation of the language. Considering you are not using CLISP, but SBCL, please fix this.

**Comment by HexF** [comment]
Propose a PR and I'll merge it in.

**Comment by dvargas46** [comment]
This was updated in V3, which is now in master.

`"aliases": ["lisp", "cl", "sbcl", "commonlisp"]`

This issue can be closed.

**Comment by HexF** [comment]
https://github.com/engineer-man/piston/blob/16f123233ba0e4f4472964ff861a2713ce41b598/packages/lisp/2.1.2/metadata.json#L4
