### ISSUE TITLE
Language Request HTML

### ISSUE THREAD

**Issue by TheSavageDev** [engineer-man/piston#205]
The [HTML](https://www.w3schools.com/html/html_intro.asp#:~:text=HTML%20stands%20for%20Hyper%20Text,how%20to%20display%20the%20content) programming language.

**Comment by HexF** [comment]
![image](https://user-images.githubusercontent.com/11236933/113574500-54e92080-9670-11eb-8101-b7d036688234.png)
Hopefully this will deter you :>

**Comment by TheSavageDev** [comment]
Hahaha

**Comment by byuilazenbyt** [comment]
It could be simple a run of a html validator...
