### ISSUE TITLE
Add html preview so users can see html they output.

### ISSUE THREAD

**Issue by ehAsuna** [engineer-man/piston#207]
Just an idea but essentially a user would enter html then it would obviously have the local host. Then from there it would take a screenshot and send it back to the user or just make a temp site or something.

**Comment by realtux** [comment]
interesting idea

**Comment by ehAsuna** [comment]
thanks i just thought it could be possible  with your knowledge

**Comment by HexF** [comment]
Too resource expensive, this would involve starting a selenium instance (basically Firefox/chrome) for every request that's wants html rendering
