### ISSUE TITLE
V3 - implement uninstall of language packages

### ISSUE THREAD

**Issue by dvargas46** [engineer-man/piston#211]
Uninstalling of packages is not implemented yet. Currently, it would have to be done manually if someone wanted to uninstall a language package.

There's a few reasons why I think it would be good to have at some point:
- **storage space**: if someone needs to remove a language because it consumes too much storage space
- **update to a language-version package**: if there ever is an update to a language-version's build/usage (might be better to implement a way to detect this at some point instead)
- **just doesn't like the language**: self explanatory
- **development purposes**: when developing new language packages locally, issues can arise while building which could lead to an erroneous package getting created and put into their local repo

Ideally, the implementation would just be to safe delete the respective target dirs/packages.

For API users, it would just be removing:
- `data/piston/packages/<language>/<version>`

Then for development/personal build maintainers, these extra ones _could_ be removed:
- `packages/<language>-<version>.pkg.tar.gz`
- everything in the `package/<language>/<version>` directory **excluding** the common build/usage scripts like `build.sh, environment, metadata.json, compile, run, test.*` (this one may technically not be necessary depending on the lang's build steps, but wouldn't hurt to add for clean rebuilds)

It doesn't need to distinguish between the different use cases of the project (probably couldn't do it accurately anyway), but just safely delete those targets and then give a nice message.

**Comment by HexF** [comment]
The final part would be impossible from within the container, as the `packages` dir doesn't get mounted into the API container.
To clean these files its possible to use `git clean`, which with the right flags can remove files which are `.gitignore`d which would mean package files.

As for uninstallation, see 81cdc766b64738cbe875c56c756332d3f3196eff for implementation.
