### ISSUE TITLE
V3 - move managing of languages impl to the CLI

### ISSUE THREAD

**Issue by dvargas46** [engineer-man/piston#212]
Just wondering if it might be best to move the implementation of the management of lang packages to the CLI instead of the API. Understandably, it's nice the way it is, but if someone using this is hosting it themselves publicly (for whatever reason) then it could open the doors to some headaches if people discover it and start installing/removing random packages using the API. Seems like more of an admin type feature IMO. 

And if it's solely implemented at the CLI, then you would have to have access to the host machine in order to manage the packages instead of dealing with authentication and tokens at the API level. There's probably a good reason for this design or maybe an easy way to secure it, but I know that v1 & v2 didn't work like this from my understanding.

Thoughts?

**Comment by HexF** [comment]
The original design for v3 to be hidden behind another API, similar to how the current piston instance on EMKC works. 
Managing languages is in the api so that it would be possible for us to manage the piston instance from EMKC, and therefore make administration of piston significantly easier.

**Comment by dvargas46** [comment]
Ok, makes sense. I can see how that will work then.
