### ISSUE TITLE
Error when running build.sh

### ISSUE THREAD

**Issue by sahar2339** [engineer-man/piston#218]
Hi, 
I am trying to install piston on ubuntu 18.4 server and I am getting this error messages from the build.sh script after compliting all the steps:

`/proc/self/fd/7: line 281:  7923 Segmentation fault      (core dumped) mix local                                                                                                                                                             .hex --force
/proc/self/fd/7: line 282:  7932 Segmentation fault      (core dumped) mix deps.                                                                                                                                                             get --force
/proc/self/fd/7: line 283:  7941 Segmentation fault      (core dumped) MIX_ENV=p                                                                                                                                                             rod mix escript.build --force
/proc/self/fd/7: line 289: /bin/mkdir: Argument list too long
/proc/self/fd/7: line 291: /usr/bin/wget: Argument list too long
/proc/self/fd/7: line 292: /bin/tar: Argument list too long
/proc/self/fd/7: line 293: /bin/rm: Argument list too long
/proc/self/fd/7: line 294: cd: swipl-8.2.4: No such file or directory
/proc/self/fd/7: line 295: /bin/mkdir: Argument list too long
/proc/self/fd/7: line 296: cd: build: No such file or directory
/proc/self/fd/7: line 297: /usr/bin/cmake: Argument list too long
/proc/self/fd/7: line 298: /usr/bin/ninja: Argument list too long
/proc/self/fd/7: line 305: /usr/bin/git: Argument list too long
/proc/self/fd/7: line 306: cd: lolcode: No such file or directory
/proc/self/fd/7: line 307: /bin/mkdir: Argument list too long
/proc/self/fd/7: line 308: cd: bin: No such file or directory
/proc/self/fd/7: line 309: /usr/bin/cmake: Argument list too long
/proc/self/fd/7: line 310: /usr/bin/make: Argument list too long
/proc/self/fd/7: line 317: /bin/mkdir: Argument list too long
/proc/self/fd/7: line 318: /usr/bin/git: Argument list too long
/proc/self/fd/7: line 319: cd: clojure: No such file or directory
/proc/self/fd/7: line 320: /usr/bin/mvn: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 334: /bin/chown: Argument list too long
/proc/self/fd/7: line 335: /bin/chmod: Argument list too long
/proc/self/fd/7: line 338: /bin/rm: Argument list too long
/proc/self/fd/7: line 339: /bin/chmod: Argument list too long
/proc/self/fd/7: line 342: /bin/systemctl: Argument list too long
/proc/self/fd/7: line 343: /bin/systemctl: Argument list too long
Error: Failed to run post-packages: exit status 126
`
I tried to change the ulimit -s to unlimited but it didn't help at all
BTW the machine I am using has 1 vCore 1Gb memory and 25Gb ssd if you think that is related 
I did something wrong?

**Comment by Sultaneous** [comment]
I was just about to post this error when I saw your post.
I have run this on two different servers with the same result.
One server has 16GB and 4 cores, with vast high-speed SSD real estate.
Scratching head on this one; but can't find a pre-built lxc image to use instead.
Help please!

**Comment by Sultaneous** [comment]
I was just about to post this error when I saw your post.
I have run this on two different servers with the same result.
One server has 16GB and 4 cores, with vast high-speed SSD real estate.
Scratching head on this one; but can't find a pre-built lxc image to use instead.
Help please!

**Comment by Sultaneous** [comment]
To expand my previous comment, it always happens after the Nim step:

Nim build detected
copying files...
installation successful
Cloning into '05AB1E'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 4157 (delta 42), reused 55 (delta 28), pack-reused 4070
Receiving objects: 100% (4157/4157), 3.56 MiB | 16.88 MiB/s, done.
Resolving deltas: 100% (2603/2603), done.
/proc/self/fd/7: line 281: 147097 Segmentation fault      (core dumped) mix local.hex --force
/proc/self/fd/7: line 282: 147106 Segmentation fault      (core dumped) mix deps.get --force
/proc/self/fd/7: line 283: 147115 Segmentation fault      (core dumped) MIX_ENV=prod mix escript.build --force
/proc/self/fd/7: line 289: /bin/mkdir: Argument list too long
/proc/self/fd/7: line 291: /usr/bin/wget: Argument list too long
/proc/self/fd/7: line 292: /bin/tar: Argument list too long
/proc/self/fd/7: line 293: /bin/rm: Argument list too long
[...]
/proc/self/fd/7: line 324: /usr/sbin/useradd: Argument list too long
/proc/self/fd/7: line 325: /usr/sbin/usermod: Argument list too long
/proc/self/fd/7: line 334: /bin/chown: Argument list too long
/proc/self/fd/7: line 335: /bin/chmod: Argument list too long
/proc/self/fd/7: line 338: /bin/rm: Argument list too long
/proc/self/fd/7: line 339: /bin/chmod: Argument list too long
/proc/self/fd/7: line 342: /bin/systemctl: Argument list too long
/proc/self/fd/7: line 343: /bin/systemctl: Argument list too long
Error: Failed to run post-packages: exit status 126

**Comment by HexF** [comment]
v3 is in master now. Use that instead of v3.
