### ISSUE TITLE
Can't Download Image: Key Error

### ISSUE THREAD

**Issue by Sultaneous** [engineer-man/piston#219]
Error:

> lxc-create -t download -n piston -- --dist ubuntu --release bionic --arch amd64
Setting up the GPG keyring
Downloading the image index
ERROR: Invalid signature for /var/lib/lxc/piston/tmp.zlJqoGb8vm/index.asc
lxc-create: piston: lxccontainer.c: create_run_template: 1616 Failed to create container from template
lxc-create: piston: tools/lxc_create.c: main: 319 Failed to create container piston

I've tried:
> DOWNLOAD_KEYSERVER="pgp.mit.edu"

Same error.  I've also tried (without success):
* keys.opengpg.org
* keyserver.ubuntu.com
* zimmermann.mayfirst.org

Anyone know how to get around this? I don't think this is a key server issue.  I just think the signature is incorrect so it can never validate it.

**Comment by HexF** [comment]
This isn't within our domain, this would be an issue directly with LXC, as all you seem to be doing is downloading ubuntu bionic for LXC.
My best guess is the index hasn't been signed yet, or the signing key has expired.
