### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by WeMayNeverKnow** [engineer-man/piston#224]
Please make api docs because it's hard to know what things return and what to do with them because we don't have the other necessary informations

I have been trying to do things with my code and still haven't done much because I kept guessing what to do

**Comment by realtux** [comment]
could you perhaps state what isn't documented that you're having a hard time using? there's only two endpoints and the signatures, request format, and response format are all in the readme.

**Comment by HexF** [comment]
Ill builld an openapi/swagger for public and private piston.

**Comment by WeMayNeverKnow** [comment]
I figured out the problem now. Since the read me has been updated.
`https://emkc.org/api/v1/execute` I keep requesting from this endpoint since it was on the readme before but I should have done `https://emkc.org/api/v1/piston/execute` 

Tho I think we could still use the docs for some examples.

**Comment by HexF** [comment]
Yeah we will get it done eventually

**Comment by HexF** [comment]
Merged into #300
