### ISSUE TITLE
Some piston languages are currently broken

### ISSUE THREAD

**Issue by nmreddy1911** [engineer-man/piston#225]
The execution for C and C++ is not working both on the public API and the challenges page in the emkc.org site.

Hoping to see it resolved.

**Comment by realtux** [comment]
it'll get fixed today

**Comment by CaiB** [comment]
C# also seems broken. Running the following from Discord:
```
/run csharp
System.Console.WriteLine("Testing the bot?");
```

Returns
```
/piston/packages/mono/6.12.0/compile: line 3: csc: command not found
/piston/packages/mono/6.12.0/run: line 5: mono: command not found
```

(Also, why is Mono being used when .NET 5 is available?)

**Comment by HexF** [comment]
yep, im aware, we are working on it.

**Comment by HexF** [comment]
> C# also seems broken. Running the following from Discord:
> 
> ```
> /run csharp
> System.Console.WriteLine("Testing the bot?");
> ```
> 
> Returns
> 
> ```
> /piston/packages/mono/6.12.0/compile: line 3: csc: command not found
> /piston/packages/mono/6.12.0/run: line 5: mono: command not found
> ```
> 
> (Also, why is Mono being used when .NET 5 is available?)

To answer your other question, both are available, select between them by using `mono` or `dotnet` as the language, simply using `csharp` picks the one with the highest version number.

**Comment by CaiB** [comment]
I see. I tried `dotnet`, and it looks like it's running the wrong tool (or maybe grabbing the wrong output?)
```
/piston/packages/dotnet/5.0.201/compile: line 6: rename: command not found
Getting ready...
The template "Console Application" was created successfully.
  Determining projects to restore...
  Restored /piston/jobs/2d423ad1-8b2b-4649-a72c-f51732664a30/2d423ad1-8b2b-4649-a72c-f51732664a30.csproj (in 120 ms).
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/piston/jobs/2d423ad1-8b2b-4649-a72c-f51732664a30/2d423ad1-8b2b-4649-a72c-f51732664a30.csproj]

Build FAILED.

CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/piston/jobs/2d423ad1-8b2b-4649-a72c-f51732664a30/2d423ad1-8b2b-4649-a72c-f51732664a30.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.28
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-bin/Debug/net5.0/2d423ad1-8b2b-4649-a72c-f51732664a30.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
  ```

**Comment by HexF** [comment]
Nah issue is the extension on the source files isn't `.cs`, the rename command in there there to fix it, but rename isn't in the container yet.

**Comment by CaiB** [comment]
Gotcha, no worries. I'll stop bothering you about it then :)

**Comment by HexF** [comment]
dotnet should have just been fixed, give it another go and tell me if it works

**Comment by HexF** [comment]
c and c++ should work now too

**Comment by CaiB** [comment]
C appears to work fine.

C# works via `dotnet` but is _really_ slow. It used to practically instant, now it's several seconds of "I Run Code is typing...", then this is the output:
```
Getting ready...
The template "Console Application" was created successfully.
  Determining projects to restore...
  Restored /piston/jobs/6b9eb0c6-56c7-4880-8b9e-eab22f4bd8e9/6b9eb0c6-56c7-4880-8b9e-eab22f4bd8e9.csproj (in 112 ms).
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  6b9eb0c6-56c7-4880-8b9e-eab22f4bd8e9 -> /piston/jobs/6b9eb0c6-56c7-4880-8b9e-eab22f4bd8e9/bin/Debug/net5.0/6b9eb0c6-56c7-4880-8b9e-eab22f4bd8e9.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.29
Testing the bot?
```

**Comment by nmreddy1911** [comment]
> 
> 
> c and c++ should work now too

Thanks @HexF , they are all good now.

**Comment by HexF** [comment]
There are 3 remaining languages which are broken:
* clojure
* groovy
* scala

**Comment by nmreddy1911** [comment]
> There are 3 remaining languages which are broken:
> * clojure
> * groovy
> * scala

Oh k

**Comment by djfinlayson** [comment]
python3 is giving me an error. 
"message":"files is required as an array"

**Comment by realtux** [comment]
you are very likely sending the request as urlencoded and not json

**Comment by djfinlayson** [comment]
Nope, just didn't realize you had updated the Public API. Thanks.

**Comment by HexF** [comment]
Everything should be working now, code away lads!
