### ISSUE TITLE
Add endpoint to get the ratelimits?

### ISSUE THREAD

**Issue by Zeref-Draganeel** [engineer-man/piston#244]
It would be much easier, if you change the ratelimits, by getting the ratelimits, our program wont break(or atleast error out)
or another solution can be to add the ratelimit in the header
like in the docs its written 5 requests / sec but its actually 1 request / 0.5 seconds

**Comment by realtux** [comment]
this is a feature worth doing when we get time as this is the normal convention for apis.

**Comment by HexF** [comment]
Would be something to throw on EMKC

**Comment by realtux** [comment]
yes, this isn't an appropriate feature for within piston itself

**Comment by HexF** [comment]
Closing as transfered to EMKC
