### ISSUE TITLE
Add Visual Basic Language (VBScript)

### ISSUE THREAD

**Issue by marcio126** [engineer-man/piston#252]

**Comment by Vrganj** [comment]
Would be possible with wine

**Comment by realtux** [comment]
i suspect that's the only option

**Comment by HexF** [comment]
https://www.mono-project.com/docs/about-mono/languages/visualbasic/
?

**Comment by HexF** [comment]
Visual Basic is compiled in to CIL, which is the same thing as C#, so it should be possible to do this with both mono and dotnet

**Comment by Brikaa** [comment]
The mono compiler we have doesn't include mono-basic. Do we download mono-basic in the same package folder or make a new folder for that?

**Comment by HexF** [comment]
Add it into the same one
