### ISSUE TITLE
Can't build gcc 10.2.0 package

### ISSUE THREAD

**Issue by dubik** [engineer-man/piston#259]
I installed piston on a VM (small) in Azure.
I launched it with `docker-compose`. 
With cli I can install new packages:
`cli/index.js ppman install rust`
I installed `python`, `rust`, `ruby` just fine. So seems that installation works ok. However I get an error when I install `gcc`.
```
azureuser@piston:~/piston$ cli/index.js ppman install gcc
piston ppman install <language> [language_version]

Installs the named package

Options:
      --version     Show version number                        [boolean]
  -u, --piston-url  Piston API URL
                             [string] [default: "http://127.0.0.1:2000"]
      --help        Show help                                  [boolean]

TypeError: Cannot read property 'data' of undefined
    at Object.exports.handler (/home/azureuser/piston/cli/commands/ppman_commands/install.js:24:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I guess node returns some error, which install.js can't handle. So I made `POST` request to `/api/v2/packages`
```
{
	"language": "gcc",
	"version": "*"
}
```
After a while, it hanged up.
Am I missing something?
I tried to build it manually, but couldn't figure out whether it happens on host or in docker. Docker image doesn't have `curl`, host doesn't have `make`. So I'm a bit confused.

**Comment by HexF** [comment]
Installing a package simply downloads it from GitHub, which could take some time
The gcc package is ~2GB iirc, so it may take a while to download, which could be causing a timeout.

**Comment by dubik** [comment]
Thanks, what would be the way to get `gcc` into piston? I couldn't figure out from where it downloads that package.

**Comment by HexF** [comment]
If you `curl` the install endpoint, it should work. Just make sure to have a sufficient timeout on curl to ensure it will download.

**Comment by dubik** [comment]
I'm not very fluent with `docker` or `nodejs`, how can I find out that endpoint?
I attached to running docker to see the logs, and got only one line (perhaps there is a way to enable debug messages, but I don't know how):
```
azureuser@piston:~/piston$ sudo docker attach be9
2021-05-18T07:11:40.654Z [INFO]  package: Installing gcc-10.2.0
```
Source code doesn't give any hints where it downloads package either:
```
const download = await fetch(this.download);
```
Documentation doesn't mention that packages are stored somewhere, are you building them when PR merged?
Also I don't think it's timeout, because this morning it was doing that for almost 700 seconds, but when I tried it again, it fails after 10-15s.

**Comment by HexF** [comment]
If you start the docker container with the flag `-e PISTON_LOG_LEVEL=DEBUG` you should be able to start the container in with debug logging. Just make sure to stop all other containers.
Packages are stored in the data directory, which is one of the `-v` commands. By default it is in `data/piston`.

**Comment by dubik** [comment]
It turns out that downloading is super quick. I added env var to docker-compose (in case someone will need this):
```
azureuser@piston:~/piston$ cat docker-compose.yaml
version: '3.2'

services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec
            - /tmp:exec
        environment:
            - PISTON_LOG_LEVEL=DEBUG
```
and got the following:
```
api_1  | 2021-05-18T07:52:19.800Z [INFO]  package: Installing gcc-10.2.0
api_1  | 2021-05-18T07:52:19.801Z [WARN]  package: gcc-10.2.0 has residual files. Removing them.
api_1  | 2021-05-18T07:52:19.814Z [DEBUG] package: Making directory /piston/packages/gcc/10.2.0
api_1  | 2021-05-18T07:52:19.815Z [DEBUG] package: Downloading package from https://github.com/engineer-man/piston/releases/download/pkgs/gcc-10.2.0.pkg.tar.gz in to /piston/packages/gcc/10.2.0
api_1  | 2021-05-18T07:52:46.850Z [DEBUG] package: Validating checksums
api_1  | 2021-05-18T07:52:46.850Z [DEBUG] package: Assert sha256(pkg.tar.gz) == b7cb10d6f1b5fb36621675d88ed991b7ebaeace395b65912302ddabf16e2ef20
```
I think that crashed javascript vm, because I got dropped to command prompt (I removed `-d`). So something doesn't work very well with sha256 calculations for big packages.

**Comment by dubik** [comment]
I guess `readFileSync()` loads whole file into memory which could be a problem. It should load file in pieces.

**Comment by HexF** [comment]
Ah well the linking closed it...

That commit should solve your issue.
