### ISSUE TITLE
same request works on public api but not local

### ISSUE THREAD

**Issue by sahar2339** [engineer-man/piston#260]
Hi,
I have remote centos instance running with piston api on it, and there is something I cant figure out.
this is the php code I am using to send the request:

```
<?php
function gethttp($body)
{
    $ch = curl_init("https://emkc.org/api/v2/piston/execute"); 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json'
));
    curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
    $data = curl_exec($ch);
    curl_close($ch);
    return $data;
}
?>
```

this is what the ($body) accepts:
```
{
    'language': "python",
    'version': '3.9.4',
    'files': [
        {
            'name': 'code.py',
            'content': 'print("hi")'
        }
    ],
    'stdin': '',
    'args': ''
}
```
And then is the weird part, when I send the same request to the public api  "//emkc.org" everything works fine. But when I replace it with my machine's IP I get (message: "Not Found") response.
Running  "**cli/index.js ppman list"** shows I have the language installed, so I tried to run **"cli/index.js run python test.py -l 3.9.4"**
and it worked just fine.

/runtimes endpoint also seems fine:
```
[{"language":"dotnet","version":"5.0.201","aliases":["cs","csharp"]},{"language":"java","version":"15.0.2","aliases":[]},{"language":"python","version":"3.9.4","aliases":["py","py3","python3"]}]
```

I tried to delete the container and start it again, nothing seems to work.
Can you tell what's happening?
Thanks!

**Comment by HexF** [comment]
Use `http://yourpistonserver /api/v2/execute `
