### ISSUE TITLE
two or more classes in one file | running in flipped order is working

### ISSUE THREAD

**Issue by piotranon** [engineer-man/piston#266]
executing this will throw error: error: can't find main(String[]) method in class: egzamin.GenericClass
/run java
```
package egzamin;

class GenericClass<T> {

     private final T pole;

     public GenericClass(T pole) {
          this.pole = pole;
     }

     public Class getMyType() {
         return this.pole.getClass();
     }
}

public class Main {
    public static void main(String [] args){
       GenericClass<Main> ala = new GenericClass<>(new Main());
       System.out.println(ala.getMyType());
    }
}
```
but executing in rotated order is working

/run java
```
package egzamin;

public class Main {
    public static void main(String [] args){
       GenericClass<Main> ala = new GenericClass<>(new Main());
       System.out.println(ala.getMyType());
    }
}

class GenericClass<T> {

     private final T pole;

     public GenericClass(T pole) {
          this.pole = pole;
     }

     public Class getMyType() {
         return this.pole.getClass();
     }
}
```

**I think that bot is searching first class and executing its main, I think it should first search main class if not found then it should search main function in first found class.**

**Comment by Vrganj** [comment]
This isn't the bot's fault, it's Java being Java. We simply can't know which class contains the main function, so we find the first class and run it.

**Comment by HexF** [comment]
https://github.com/engineer-man/piston/blob/c0b218f47791117867feb4e5bb53eef6a4e67e9e/packages/java/15.0.2/run#L7
We simply call java, so we can't fix this ourselves.
