### ISSUE TITLE
Install multiple runtimes in a single post request to packages

### ISSUE THREAD

**Issue by Atharva8** [engineer-man/piston#270]
As far as I know we can currently install a single runtime by sending a post request to api's packages endpoint.I have added the functionality to install multiple runtimes using the packages endpoint. We can send a post request containing the following : 
```
{"runtimes":[{"language":"python","version":"3.9.1"},{"language":"rust","version":"1.50.0"}]}
```
the server will loop through each runtime and install it, on succeeding it will add that to an `installed` list and the failed ones in the `failed` list with their for failing:
```
{
    "message": {
        "pass": [
            {
                "language": "python",
                "version": "3.9.1"
            },
            {
                "language": "rust",
                "version": "1.50.0"
            }
        ],
        "fail": []
    }
}
```

Is this a reasonable enhancement? If it is can you assign it to me?

**Comment by HexF** [comment]
I can't see a proper reason, something like this could be implemented in the CLI maybe, but not in the API.

To implement it in the CLI i would recommend doing what apt does when specifying versions, where you put the version after an =.

**Comment by Atharva8** [comment]
Ok great. Will start working on it

**Comment by HexF** [comment]
#272
