### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by dthree** [engineer-man/piston#275]
~~Separation of Build & Execution in Compiled Languages~~
## Benchmarking

I'm not sure if it would be trivial or not to consider adding an API flag to separate out the build and execution steps for compiled languages (let's take Go).

As part of the code playground I'm building with Piston at the back, I would like to support running benchmarking methods in multiple languages. So for this, you would want to compile the Go code once, and then run it many times.

I think the biggest issue to this would be avoidance of server side state, you wouldn't want to turn this into two requests (and require the server to remember the compile code, a no-go), and you definitely don't want to send the compiled program back to the client.

I'm just winging it as I type this. Possibly the only way to do this well without introducing state is to create a benchmark API, which can be supported on a per-language basis by adding to the language defs (maybe this isn't even necessary), and then common params like max runtime, samples, etc.

If you guys @realtux, @HexF are up to it, I wouldn't mind diving in and doing the work on this. I recently did a number to benchmark JS in a browser service worker, so I've done a lot of research on good practices for benchmarking. It would be a standalone feature, basically a third API call to add to the existing two. 

What do you think?

**Comment by realtux** [comment]
my first thought would be that this is outside of the scope of what piston is trying to accomplish. another challenge here is that piston has necessary overhead which is the trade for execution safety. using piston to benchmark wouldn't be a very accurate measurement of anything. i'm willing to hear more but i'm not sold on this at first glance.

**Comment by dthree** [comment]
Understood, but let me play with it a bit and maybe I can make a small, elegant solution. There's ways to mitigate the overhead (like process creation), such as running benchmarks on an empty process and subtracting the overhead. You're right, maybe it won't tell us anything, but it would be nice if it also offered benchmarking with no additional work for all languages!

**Comment by dthree** [comment]
Parking this for now, may have found another solution earlier on the pipeline than Piston. 👍🏻
