### ISSUE TITLE
Add example code for languages

### ISSUE THREAD

**Issue by the-codeboy** [engineer-man/piston#289]
First of all I have to say how amazing this project is! I already like the project itself but the fact that it has a free api which doesn´t even have the requirement to sign up for a key just blows my mind so thank you for that!

Now for my issue which is actually just a suggestion:

The runtimes endpoint currently returns some information about each language and my idea was to add another optional parameter to return which contains an example for a hello world programm in this language. So in javascript this would return `console.log("Hello, World!")`, in python `print("Hello, World!")`  and in brainfuck` -[------->+<]>-.-[->+++++<]>++.+++++++..+++.[->+++++<]>+.------------.---[->+++<]>.-[--->+<]>---.+++.------.--------.-[--->+<]>.`

I´d love to add this myself but when I was reading through the code I got a little confused. My plan was to add a variable called hello_world (could also be something different I´m not familiar with the naming conventions of node) which would default to an empty string. The only place I found where the class Runtime is instantiated is in load_package which reads the information from a file called "pkg-info.json" from the package directory. However I was not able to find a file called "pkg-info.json" anywhere in this repo

**Comment by HexF** [comment]
I can't exactly see the use case for this, we already include a test for each language which outputs "OK", which should be enough?

**Comment by the-codeboy** [comment]
The use case for my idea would not be to test if the language is working but to give a user of the api a way to get a short demo of what the language looks like. This could be useful for anyone who uses piston to make some kind of code editor where you can select multiple languages since you can just paste the example code when the user changes the language.

Of course the example code that gets send doesn´t have to output hello world so you could just use the code used for testing if that´s what you mean

**Comment by HexF** [comment]
Querying a URL such as
https://raw.githubusercontent.com/engineer-man/piston/master/packages/brainfuck/2.7.3/test.bf
you can get the content of a script which outputs `OK`, and therefore I still can't see a need for this sort of feature.

**Comment by the-codeboy** [comment]
There is no way to find this url since you can´t get the file extension from the api so no that´s not a solution

**Comment by HexF** [comment]
You can, the list of aliases contains one of the extensions - usually the shortest one.

**Comment by the-codeboy** [comment]
That doesn´t always work for example with bash where the only alias is sh but the name of the file which should be test.sh is actually test.bash.sh

I actually just wanted to contribute to this project and I felt like this would have been a useful feature to add but it seems like contributions like this aren´t welcome

**Comment by HexF** [comment]
Its not that contributions aren't welcomes, its that the need for this features if very limited, and if we fill the API with bloat, it over time will lose its speed to feature creep.
