### ISSUE TITLE
Container code doesn't change , when I modify  the source code in my local machine

### ISSUE THREAD

**Issue by Md-Aashiqq** [engineer-man/piston#291]
I want an add a new API in src/api/v2.js. I made all the changes and rerun the container but it doesn't affect the container
code. I didn't know how to achieve this one.

so kindly help me with this problem.

**Comment by HexF** [comment]
make sure you switch to dev with `./piston switch dev` then you can run `./piston docker_compose build` and `./piston docker_compose up`
