### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by Rashik4567** [engineer-man/piston#292]
When trying to use piston cli to list and install runtimes it gives an error ```Error: Cannot find module 'fs/promises'```
I searched stackoverflow, and the most likely answer is related to version to nodejs. It says, 
> The error was due to unsupported Node version 12.x which doesn't support this require statement...
> var promises_1 = require("fs/promises");    // does not work in node 12.x
> var promises_1 = require("fs").promises;    // works.

**Comment by realtux** [comment]
we just need to update the docs to say node.js >= v12

**Comment by eriky** [comment]
I get the same error, and I'm running Node.js v12.21.0

**Comment by HexF** [comment]
Try Node.js v13

**Comment by HexF** [comment]
I should add, this was developed on Node v15

**Comment by eriky** [comment]
OK that's it then, thanks. I upgraded to 16 and it now works. For anyone who needs instructions and I on Debian/Ubuntu, use this: https://github.com/nodesource/distributions#installation-instructions
I recommend completely uninstalling all nodejs related packages first though
