### ISSUE TITLE
How would you recommend self-hosting/deploying piston?

### ISSUE THREAD

**Issue by mehmetron** [engineer-man/piston#295]
Are there any things I should keep in mind?

It seems ```docker-compose up api ``` uses a pulled piston docker image and disregards any custom changes I made locally. 

So I plan to run ```docker-compose -f docker-compose.dev.yaml up``` 

Is this ok? Is there a better way?

**Comment by HexF** [comment]
The docker-compose file we provide is ment to be used as a starting point, and should be modified according to your needs.

What sort of tweaks have you made to the image locally?

**Comment by mehmetron** [comment]
I didn't do much. Just fixed some cors issues I was having. I put that fix in a pull request in case you guys also experience issues.
I was thinking about adding support for installing packages but don't know where I'd begin. I'm just going to tinker

**Comment by HexF** [comment]
Installing packages works as is, it's just not documented as its not a feature that should be commonly used.
As for CORS see the PR #296 for information

**Comment by dthree** [comment]
I'd like to write a doc on this for the repo, if you'd like @HexF, as I went through this recently and there's a few gothcas.

**Comment by HexF** [comment]
Sure, go for it, PR them in

**Comment by HexF** [comment]
Seems to have been resolved a while back - closing
