### ISSUE TITLE
Inappropiate "SIGKILL".

### ISSUE THREAD

**Issue by Rashik4567** [engineer-man/piston#301]
As defined in readme, it should sigkill if the code has unexpected behaviour. But if you run this python code, you will get sigkill: 
```python
for i in range(1626):
    print("Hello world")
```

But the same code just in a different syntax and language will work, like in python: 
```python
output = ''
for i in range(1626):
    output += "Hello world\n"
print("Hello world")

# OR THIS WILL ALSO WORK 
print("Hello world\n" * 1626)

```
and this in c also works: 
```c
#include "stdio.h"
int main() {
  for (int i = 0; i < 1626; i++) {
    printf("Hello world");
  }
return 0;
}
```

It all does the same but IDK why the first one doesn't work. Its trigerring SIGKILL with code null.

**Comment by HexF** [comment]
This is totally normal - it's SIGKILLing because there is run away output, exceeding 1024 characters in length.
Currently there is a bug causing an 88 char over run, but that's besides the point. 

This is done to ensure we aren't sending gigabytes of data back for a simple `dd if=/dev/zero of=/dev/stdout`

**Comment by Rashik4567** [comment]
Then why does the other 3 work?

**Comment by Rashik4567** [comment]
And also it should not be 1024 chars.. 
![image](https://user-images.githubusercontent.com/58215479/126338066-180b4137-2cb9-4a4e-a5fc-58802bdc4094.png)

**Comment by HexF** [comment]
We have it set at 1024 chars on public piston, if you wish to change it, run your own instance and configure it accordingly

**Comment by Rashik4567** [comment]
> We have it set at 1024 chars on public piston, if you wish to change it, run your own instance and configure it accordingly

How to config?|

**Comment by Rashik4567** [comment]
I have my own instence running.

**Comment by HexF** [comment]
https://piston.readthedocs.io

**Comment by AASHIK-2512** [comment]
getting same *SIGKILL* issue in java code to what is the fix can any one tell? this same code mostly running but sometimes getting code 0 and signal = SIGKILL

##piston response

{
    "language": "java",
    "version": "15.0.2",
    "run": {
        "stdout": "",
        "stderr": "",
        "code": null,
        "signal": "SIGKILL",
        "output": ""
    }
}



##my code:- 

 import java.util.*;
    import java.util.HashSet;
    import java.util.PriorityQueue;


    public class Main {
        public static void main(String[] args) {
    {
        ListNode head = new ListNode(1, new ListNode(2, new ListNode(3, new ListNode(4, new ListNode(5)))));

        Solution solution = new Solution();
        ListNode result = solution.reverseList(head);
        System.out.print("[");
while (result != null) {
    System.out.print(result.val);
    if (result.next != null) System.out.print(",");
    result = result.next;
}
System.out.println("]");

    }
    {
        ListNode head = new ListNode(1, new ListNode(2));

        Solution solution = new Solution();
        ListNode result = solution.reverseList(head);
        System.out.print("[");
while (result != null) {
    System.out.print(result.val);
    if (result.next != null) System.out.print(",");
    result = result.next;
}
System.out.println("]");

    }
    {
        ListNode head = null;

        Solution solution = new Solution();
        ListNode result = solution.reverseList(head);
        System.out.print("[");
while (result != null) {
    System.out.print(result.val);
    if (result.next != null) System.out.print(",");
    result = result.next;
}
System.out.println("]");

    }
        }
    }
class ListNode {
    int val;
    ListNode next;
    ListNode() {}
    ListNode(int val) { this.val = val; }
    ListNode(int val, ListNode next) { this.val = val; this.next = next; }
}


@SuppressWarnings("unchecked")class Solution {
    public ListNode reverseList(ListNode head) {
    ListNode prev = null;
    ListNode current = head;
    while (current != null) {
        ListNode next = current.next;
        current.next = prev;
        prev = current;
        current = next;
    }
    return prev;
}
}
