### ISSUE TITLE
Add support for directories

### ISSUE THREAD

**Issue by a1g3** [engineer-man/piston#302]
I'm currently using Piston to run Python code.  Python uses directories to distinguish other packages (Java also uses directories to distinguish packages) .  I tried to specify a relative path in the file.name parameter like "folder/input.py".  When I tried to send this to the server, the API breaks [here](https://github.com/engineer-man/piston/blob/968390d5b69973ebdd56a35bb545fc864c53a586/api/src/job.js#L61-L64).  The log contains the following error: 
```
[INFO]  job: Priming job uuid=ebc3b7c6-943a-4953-8161-8ba4b818f8f8
[DEBUG] job: Writing files to job cache
[DEBUG] job: Transfering ownership uid=1001 gid=1001
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open '/piston/jobs/ebc3b7c6-943a-4953-8161-8ba4b818f8f8/folder/input.py'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/piston/jobs/ebc3b7c6-943a-4953-8161-8ba4b818f8f8/folder/input.py'
}
```
It seems like Piston doesn't support the relative directories like how I'm trying to use it.  Is it possible to add support for adding source files in other directories?

**Comment by realtux** [comment]
can you supply the request body you made to the api?

**Comment by HexF** [comment]
This is indeed a bug, I'll get on fixing it

**Comment by a1g3** [comment]
Here is the request body:

```json
{"language": "py", "version": "3.9.4", "files": [{"name": "input.py", "content": "print(\"Hello World\")"}, {"name": "in/demofile.txt", "content": "File Content"}]}
```
