### ISSUE TITLE
[Java] Semi-colon breaks literals for strings & characters

### ISSUE THREAD

**Issue by discorddioxin** [engineer-man/piston#305]
## Reproduce

> /run \`\`\`java
> var s = ";";
> \`\`\`

### Expected
_No output_

### Actual

> file0.code.java:2: error: unclosed string literal
var s = ";
>         ^
> file0.code.java:3: error: unclosed string literal
";
> ^
> 2 errors
> error: compilation failed

## Notes
Works in any situation where a string literal contains a semi-colon
> /run \`\`\`java
> System.out.print("test;");
> \`\`\`

Also affects character literals in the same way
> /run \`\`\`java
> var c = ';';
> \`\`\`

**Comment by dvargas46** [comment]
This is an issue with the IRC bot's java template. Piston runs that code just fine (with proper boilerplate ofc).

Try reporting your issue over on the [piston-bot](https://github.com/engineer-man/piston-bot) project.
