### ISSUE TITLE
Add C#

### ISSUE THREAD

**Issue by winner-com** [engineer-man/piston#307]
Provide links to different compilers/interpreters that could be used to implement this language, and discuss pros/cons of each.

**Comment by HexF** [comment]
We already have C# via both mono and dotnet

**Comment by winner-com** [comment]
But, it show 
Error
Unsupported language:
c# Request a new language

![96E3E2CA-7F95-4000-B36C-2DA5C4D79E4C](https://user-images.githubusercontent.com/83830228/129666124-76d10788-e0ff-409b-a24d-82f51e000425.jpeg)

**Comment by realtux** [comment]
for now replace `c#` with `csharp`, we're missing an alias for `c#`
