### ISSUE TITLE
Add [C#] for compiling, i don't know if your support, so this request is more like a question

### ISSUE THREAD

**Issue by AizonF** [engineer-man/piston#310]
Does piston support compiling C#? with php

**Comment by Poultryghast** [comment]
Piston supports C# with the aliases dotnet and  mono.

**Comment by HexF** [comment]
yep, we should add `c#` to the aliases

**Comment by Brikaa** [comment]
c# is already an alias in mono (#230), maybe the mono package info file needs to be rebuilt.
