### ISSUE TITLE
Accessing Stdin & Args from content

### ISSUE THREAD

**Issue by saldagmac** [engineer-man/piston#311]
I'm interested in using Piston, but there seems to be some issues with accessing stdin and args once the code I've sent to Piston is trying to execute.

Say that I've sent a post whose content is "console.log(process.argv)" like in the example; The result is that I get a print out of all args.... Except that argv[0] and argv[1] appear to be paths. Not an issue per se, but that should be noted somewhere in the documentation. However, much more of an issue, is that if my request to Piston has args: "beta", I just want to send a single string "beta" as an argument to the code being run, argv being printed out results in this:
[ <Path1>, <Path2>, 'b', 'e', 't', 'a']
Am I missing something huge? How can I have process.argv[2] be "beta", and not just 'b' in this example>

Another issue: console.log(process.stdin) results in a large object being printed out, but there is no inclusion of the data I've sent as STDIN. How, at least in Javascript, is the user expected to access the data that was presumably sent over through STDIN?
Especially if it varies by language, this really warrants some documentation, if not examples, on how the content is meant to call upon the supplemental data passed in through STDIN and ARGS.

Can anyone either explain the correct way to go about this, or confirm that this feature isn't yet fully supported?

**Comment by realtux** [comment]
two things:

first, what `argv[0]` refers to is different per language, this isn't really up to piston. if you are using node.js, process.argv[0] will refer to the path to the node binary, that's just how they do things.

second, args and stdin is fully supported and if you are doing `"args": ["beta"]` then `process.argv[1]` should just be the string "beta". to debug that further, please supply the request body you are making to piston.

**Comment by saldagmac** [comment]
{
  "language": "javascript",
  "version": 16.3.0",
  "files": [
    {
      "name": null,
      "content": "console.log(process.argv[2])"
    }
   ],
  "stdin": "Data",
  "args": "[beta]",
  "compile_timeout": 0,
  "run_timeout": 0,
  "compile_memory_limit": -1,
  "run_memory_limit": -1
}

When this runs, I get '['. If I change '[beta]' to 'beta', then I get 'b'.

**Comment by realtux** [comment]
it needs to be `"args": ["beta"]`

**Comment by saldagmac** [comment]
Thank you, I will give that a shot.

**Comment by saldagmac** [comment]
That did indeed fix it, thank you very much for the quick response!
