### ISSUE TITLE
Failed to fetch when installing

### ISSUE THREAD

**Issue by Attacler** [engineer-man/piston#37]
When i try to do the following step:

# install all necessary piston dependencies

The following error comes up: (when running apt-get update)

root@piston:/# echo 'source /opt/.profile' >> /opt/.bashrc
root@piston:/# echo 'export HOME=/opt' >> /opt/.profile
root@piston:/# echo 'export TERM=linux' >> /opt/.profile
root@piston:/# echo 'export PATH=$PATH:/opt/.local/bin' >> /opt/.profile
root@piston:/# export HOME=/opt
root@piston:/# export TERM=linux
root@piston:/# sed -i 's/\/root/\/opt/' /etc/passwd
root@piston:/# sed -i \
>     's/http:\/\/archive.ubuntu.com\/ubuntu/http:\/\/mirror.math.princeton.edu\/pub\/ubuntu/' \
>     /etc/apt/sources.list
root@piston:/# apt-get update
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://mirror.math.princeton.edu/pub/ubuntu bionic InRelease
  Temporary failure resolving 'mirror.math.princeton.edu'
Err:3 http://mirror.math.princeton.edu/pub/ubuntu bionic-updates InRelease
  Temporary failure resolving 'mirror.math.princeton.edu'
Reading package lists... Done
W: Failed to fetch http://mirror.math.princeton.edu/pub/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'mirror.math.princeton.edu'
W: Failed to fetch http://mirror.math.princeton.edu/pub/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'mirror.math.princeton.edu'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'

Im on a debian VPS, can someone help me out?

**Comment by realtux** [comment]
i think the shift of this issue is to do a test install for debian. will get back to this when i do.

**Comment by HexF** [comment]
Issue is no networking is configured, see: [https://wiki.debian.org/LXC#Networking](https://wiki.debian.org/LXC#Networking) for more information

**Comment by realtux** [comment]
closing in favor of #75
