### ISSUE TITLE
Minor nit- Platforms

### ISSUE THREAD

**Issue by Lewiscowles1986** [engineer-man/piston#38]
https://github.com/engineer-man/piston/blob/master/var/install.txt#L19 mentions debian/arch/mac os

You have Arch 😂 debian should be analogous to Ubuntu. Ubuntu is based from Debian. I am 99% certain the packages you install have the same names. OSx would run in a VM, which could be any of the above three (that is how docker on osx works).

## Suggestion

Remove at least arch. Maybe debian. Maybe make a docker image using alpine so Mac users can do something almost as easy as `brew install` (`docker run ...`)

**Comment by Vrganj** [comment]
There's been some talk about making a ubuntu image for easier setup, because setting up lxc properly is a pain in the ass. I doubt there's going to be an alpine image any time soon, though.

**Comment by realtux** [comment]
docker adds too much complexity, i'll be releasing an lxc image and i suspect it can be imported anywhere lxc is supported

**Comment by realtux** [comment]
n/a now since v3 is docker
