### ISSUE TITLE
Accept Standard Input

### ISSUE THREAD

**Issue by azimjohn** [engineer-man/piston#39]
For example:
```
{
	"input": "there",
	"source": "print('hello ' + input())",
	"language": "python"
}
```
should respond with
```
{
  "ran": true,
  "language": "python",
  "version": "3.6.9",
  "output": "hello there"
}
```

**Comment by azimjohn** [comment]
If this feature gets selected for development, I can help with it.
Thanks!

**Comment by realtux** [comment]
this is actually a planned feature already. for backwards compatibility, a new field called `stdin` will be added.

**Comment by realtux** [comment]
implemented
