### ISSUE TITLE
Add more html support

### ISSUE THREAD

**Issue by Yaumama** [engineer-man/piston#394]
What would be cool would be if you use the html language it would make a document out of the code you put and send the link of the document in the chat

**Comment by HexF** [comment]
This doesn't need to be a core feature.
Piston can provide the HTML out on the `run.stdout` parameter, and this could be hosted by another web server.

This is out of scope of piston, and as such will be closing the issue.

**Comment by tsukuyomm** [comment]
sounds like a free way to get static hosting lmao

**Comment by Yaumama** [comment]
> sounds like a free way to get static hosting lmao

wait I never thought of that lmao

**Comment by realtux** [comment]
it's an interesting idea and it has been talked about before, but in the end it's simply not what piston is for. it's a little too divergent from how everything else works.
