### ISSUE TITLE
Different Field for Std Err

### ISSUE THREAD

**Issue by azimjohn** [engineer-man/piston#40]
For example:
```
{
	"input": "there",
	"source": "print('hello' + 1)",
	"language": "python"
}
```
should probably respond with
```
{
  "ran": true,
  "language": "python",
  "version": "3.6.9",
  "output": "",
  "error": "Traceback (most recent call last):\n  File \"code.code\", line 1, in <module>\n    print('hello' + 1)\nTypeError: can only concatenate str (not \"int\") to str"
}
```

**Comment by azimjohn** [comment]
If this feature gets selected for development, I can help with it.
Thanks!

**Comment by realtux** [comment]
this is actually a planned feature already. for backwards compatibility `output` will stay as is and two new fields `stdout` and `stderr` will be introduced.

**Comment by TitouanT** [comment]
I guess this issue should be closed since `stdout` and `stderr` are now part of the response :)
This was a quick transformation from planned to implemented !

**Comment by Vrganj** [comment]
Yep, next on the list is stdin, which won't be hard, but will require a lot of copy pasting
