### ISSUE TITLE
Add MATL

### ISSUE THREAD

**Issue by Hydrazer** [engineer-man/piston#408]
MATL is a golfing language based on MATLAB/octave repo here https://github.com/lmendo/MATL/

**Comment by VlaDexa** [comment]
This compiler is based on MATLAB, which is not a free program, so I see no way of implementing this

**Comment by HexF** [comment]
Would octave work for running this?

**Comment by Hydrazer** [comment]
Yeah octave works I already have it working I’m just waiting for brachylog pr

**Comment by Hydrazer** [comment]
well i stole the idea from dennis lol https://github.com/TryItOnline/tiosetup/blob/master/languages/matl
https://github.com/TryItOnline/tryitonline/blob/master/wrappers/matl
