### ISSUE TITLE
Add [nasm assembly]

### ISSUE THREAD

**Issue by benbongty** [engineer-man/piston#409]
Provide links to different compilers/interpreters that could be used to implement this language, and discuss pros/cons of each.

**Comment by HexF** [comment]
![image](https://user-images.githubusercontent.com/11236933/144395374-e094f1e5-238f-4e96-86b7-3d4f1edc7782.png)
"Did you mean [nasm](https://github.com/engineer-man/piston/tree/master/packages/nasm/2.15.5)"
