### ISSUE TITLE
Can't connect to piston with local docker image on Mac OS Catalina

### ISSUE THREAD

**Issue by ShaneLee** [engineer-man/piston#418]
Hi, 

Thanks for this incredible project - it's awesome

Closest other issue this one: https://github.com/engineer-man/piston/issues/183 

I suspect this is just user error on my part.

I'm trying to get piston to work locally as a docker image. I've followed these instructions from the read me:

```
# clone and enter repo
git clone https://github.com/engineer-man/piston
Installation
# Start the API container
docker-compose up -d api

# Install all the dependencies for the cli
cd cli && npm i && cd -
```

All of that works, and I can install packages with ``` cli/index.js ppman install python```

Which I can verify with ```cli/index.js ppman list```  and the container is up on port 2000: ` 0.0.0.0:2000->2000/tcp`

The problem is that I can't connect to piston via chrome or ping. 

`ping 127.0.0.1:2000/api/v2/piston/runtimes` returns `ping: cannot resolve 127.0.0.1/api/v2: Unknown host` and in chrome just returns the not found message. 

I'm running Mac OS Catalina, which may be the problem. 

Any help would be greatly appreciated

Thanks

Shane

**Comment by ShaneLee** [comment]
Also side issue - can anyone help point me in the right direction with the specfiles? I  can't find an example of one to build a custom piston image with 

```
6:    echo "Usage: $0 [specfile] [tag]"
35:    # Evalulate the specfile
47:[ -z "$SPEC_FILE" ] && help_msg "specfile is required"
50:[ -f "$SPEC_FILE" ] || help_msg "specfile does not exist"

cli/commands/ppman_commands/spec.js
6:exports.command = ['spec <specfile>'];
21:exports.handler = async ({ axios, specfile }) => {
22:    const spec_contents = await fs.readFile(specfile);
```

There's nothing in the docs either: https://piston.readthedocs.io/en/latest/search.html?q=specfile

**Comment by dvargas46** [comment]
Take off "piston" from the url. That's only used in the public proxy, not local instances.

All browsers perform a GET request when "going" to a url, so you'd only be able to check the runtimes endpoint there without a proper webapp.

And ping is for host checks . Use something like netcat for checking the port connection, if you need. Else just fire off a request to the right endpoint and see what happens. :)

Hope that gets ya going.

**Comment by ShaneLee** [comment]
Cheers that's worked - I thought I'd have missed something daft

Thanks again
