### ISSUE TITLE
HTML Screenshot

### ISSUE THREAD

**Issue by Yaumama** [engineer-man/piston#421]
It would be cool if I run code sent a screenshot of the document generated by html instead of outputting the code.

**Comment by HexF** [comment]
This would involve launching a headless browser to render the code, which is more resources that its worth.
Out of scope for piston, so closing issue.

**Comment by Yaumama** [comment]
Yeah I guess that is true, but I really want I run code to actually support HTML in one way. Not sure how it's going to work though.
