### ISSUE TITLE
Deploying it on AWS

### ISSUE THREAD

**Issue by saifkhan7865** [engineer-man/piston#422]
Hey does any one have any experience or know the process of deploying engineer-man code engine on AWS , for a self hosted solution...from what I know we just need to upload the docker-compose.yml file on elastic beanstalk on a docker environment and it will take care of all the stuff (but I dont think that this is enough for engineer-man).

 Please let me know if any one knows about the process of uploading it.

Thanks in advanced

**Comment by dthree** [comment]
Hi, I had to do this.

**Comment by saifkhan7865** [comment]
thanks man I'll give this thing a try ^^

**Comment by HexF** [comment]
For any further support join the discord and we can help you out
https://discord.gg/engineer-man
