### ISSUE TITLE
api/v1/piston/version 404

### ISSUE THREAD

**Issue by necrogami** [engineer-man/piston#43]
When trying to call the version api listed in the readme it returns a 404 error

![image](https://user-images.githubusercontent.com/33020/104764621-a64ed700-5735-11eb-80f9-442440ced42d.png)

**Comment by ThreshMain** [comment]
Page for versions is [Versions](https://emkc.org/api/v1/piston/versions) not https://emkc.org/api/v1/piston/version

**Comment by necrogami** [comment]
This appears to have been a typo issue.
