### ISSUE TITLE
discord bot not running php

### ISSUE THREAD

**Issue by necrogami** [engineer-man/piston#44]
![image](https://user-images.githubusercontent.com/33020/104767082-9df89b00-5739-11eb-9eab-16d35fc9d34e.png)

**Comment by realtux** [comment]
you need to add `<?php`

**Comment by ccall48** [comment]
@necrogami try like this.
![2CDD00A6-A162-46BA-8861-62895E55D02C](https://user-images.githubusercontent.com/34887996/104792448-947f3980-57f2-11eb-9e6f-456876baa965.jpeg)

**Comment by realtux** [comment]
assuming resolved
