### ISSUE TITLE
/piston/packages/gcc/10.2.0/run: line 6: ./a.out: No such file or directory

### ISSUE THREAD

**Issue by talhabalaj** [engineer-man/piston#455]
I am trying to run C++ code using piston on my Kubernetes cluster. It doesn't work and outputs the following error.
```
/piston/packages/gcc/10.2.0/run: line 6: ./a.out: No such file or directory
```
Even on local env, it errors out and says
```
/piston/packages/gcc/10.2.0/run: line 6: ./a.out: Permission Denied
```

I tried python, it works.

**Comment by talhabalaj** [comment]
nvm, it started working now. :\

**Comment by realtux** [comment]
it should have gave you the compilation errors, did it not?

**Comment by HexF** [comment]
I think there is room for improvement here, notably not running code if the compiling stage errors out, which would reduce this confusion seen here.

**Comment by talhabalaj** [comment]
> it should have gave you the compilation errors, did it not?

It may have, but i was just returning "run.output" from my API and didn't take into account that I am giving it code with syntax errors.
