### ISSUE TITLE
Add runtime info in the Response from /execute

### ISSUE THREAD

**Issue by CaffeineDuck** [engineer-man/piston#463]
It would be helpful to have info like:
- `memory_usage`
- `execution_time`
- ...

in the response from `/execute`

**Comment by sprakhar77** [comment]
Is there any update on this one?

**Comment by realtux** [comment]
> Is there any update on this one?

pull requests always welcome :)

**Comment by vsecoder** [comment]
look this: https://github.com/engineer-man/piston/pull/645

**Comment by smark-1** [comment]
#683 adds this

**Comment by Brikaa** [comment]
More info here: https://github.com/engineer-man/piston?tab=readme-ov-file#execute-endpoint
