### ISSUE TITLE
Can we get how much a program took to execute in Piston?

### ISSUE THREAD

**Issue by gouseferoz** [engineer-man/piston#464]
Is there a way to record the time took for a program to execute in piston?

**Comment by Vrganj** [comment]
Not as of right now, but it would be trivial to implement. I suppose you can check how long it takes for the request to finish, but that includes the network latency. Though, a pull request would be appreciated.

**Comment by realtux** [comment]
the problem with this is the resulting execution time wouldn't be overly useful right now. piston by default is optimized for safety and availability. execution speed is directly related to the resources involved in the execution, which vary greatly between machines and is limited in the piston execution environment (for safety). to get consistent execution numbers that are unbound by limits would require piston supporting a sort of unsafe environment that has unlimited resources and no time limits. this is something piston doesn't currently support but may in the future, although there's no plans to do so at the moment.

**Comment by crbonilha** [comment]
even though resources are limited (for safety), aren't they limited consistently across multiple runs on the same machine?
if so, then having the runtime information on the response would be useful.

**Comment by smark-1** [comment]
#683 adds to the execution response the `cpu_time`, `wall_time`, and `memory`

**Comment by Brikaa** [comment]
More info here: https://github.com/engineer-man/piston?tab=readme-ov-file#execute-endpoint
