### ISSUE TITLE
Python code is not iterating for more than 1860

### ISSUE THREAD

**Issue by gouseferoz** [engineer-man/piston#465]
Hi,

Below is my python code which I am trying to print `2000` numbers for no reason. When I run this code, I see only 1860 and with SIGKILL error. Can anyone point me to what's happening and is there some setting I need to tweak to get this working?

Python code:
```
for i in range(1,3000):
    print(i)
```

Piston Output:
```
{
  run: {
    stdout: '1\n' +
      '2\n' +
       ......
      '1859\n' +
      '1860',
    stderr: '',
    code: null,
    signal: 'SIGKILL',
    output: '1\n' +
      '2\n' +
      .......
      '1859\n' +
      '1860'
  },
  language: 'python',
  version: '3.10.0'
}
```

Options:
```
"compile_timeout": 10000,
"run_timeout": 3000,
"compile_memory_limit": -1,
"run_memory_limit": -1
```

**Comment by HexF** [comment]
There is a set limit on character output through stdout/stderr to prevent code from generating say, gigabytes of output to be sent.
You can disable this through setting environment variables as in [the docs](https://piston.readthedocs.io/en/latest/configuration/#output-max-size)

**Comment by HexF** [comment]
> @HexF I have doubled the output max size to 2048 and set the env variable `PISTON_OUTPUT_MAX_SIZE`. I still see the same output.

Can you show me the docker-compose file you have, and ill see if I can replicate it on my machine.

**Comment by gouseferoz** [comment]
> > @HexF I have doubled the output max size to 2048 and set the env variable `PISTON_OUTPUT_MAX_SIZE`. I still see the same output.
> 
> Can you show me the docker-compose file you have, and ill see if I can replicate it on my machine.

```
version: '3.2'

services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec
            - /tmp:exec
        environment:
            - PISTON_OUTPUT_MAX_SIZE=4096```
