### ISSUE TITLE
Make version optional

### ISSUE THREAD

**Issue by aboqasem** [engineer-man/piston#466]
Is it ok to make the version optional, if not present it defaults to the latest version?

**Comment by HexF** [comment]
While it doesn't break existing API compatibility, I think it is good practice, in this case, to force the user to provide a version selector.
I can't see the necessity for such a change, is there any specific motive for this?

**Comment by aboqasem** [comment]
I am developing a sort of examination system and the version is not necessary just like in LeetCode and other coding platforms. So instead of storing a version that could be outdated in the database I thought maybe just store the language only. It could be solved from my side by getting runtimes and getting the current version of the stored language. But that would require me to request `/runtimes` every time I want to execute.

**Comment by Brikaa** [comment]
You could put '*' in the version to get the latest one.

**Comment by HexF** [comment]
> I am developing a sort of examination system and the version is not necessary just like in LeetCode and other coding platforms. So instead of storing a version that could be outdated in the database I thought maybe just store the language only. It could be solved from my side by getting `/runtimes` and getting the current version of the stored language. But that would require me to request `/runtimes` every time I want to execute.

As Brikaa said, you can use a `*` which is a SemVer selector for any version, which on piston will resolve to the latest version.
If you don't need to store the language, you can simply just always pass in `*`.

**Comment by aboqasem** [comment]
Oh, I did not know about that! Thank you all, will do it like that then.
