### ISSUE TITLE
Bug with gcc

### ISSUE THREAD

**Issue by azimjohn** [engineer-man/piston#480]
I am occasionally getting the following error while running C++ code.
```
/piston/packages/gcc/10.2.0/run: line 6: ./a.out: No such file or directory
```
I tried to run the same code after some time. It compiled without errors.

**Comment by Brikaa** [comment]
What was the code you tried to run?

**Comment by azimjohn** [comment]
@Brikaa 
```cpp
#include <iostream>

bool is_power_of_two(int num){
    return (num & (num - 1)) == 0;
}

int main() {
    int n;
    cin >> n;
    while (n--) {
        int num;
        cin >> num;
        cout<< is_power_of_two(num) ? 1:0 << endl;
    }
    return 0;
}

```

**Comment by Brikaa** [comment]
Could you check stdout and stderr in the 'compile' section in the returned result when you get this error?

**Comment by azimjohn** [comment]
@Brikaa compile error now makes sense, thanks for helping out with the issue!
