### ISSUE TITLE
Jobs have write permission in the /piston/jobs directory.

### ISSUE THREAD

**Issue by Swiddis** [engineer-man/piston#487]
## Expected Behavior
The only directory accessible to a script should be the script's home directory, `/piston/jobs/{UUID}`. Preferably there would be no read permission outside of this directory, but avoiding write-access is sufficient.

## Current Behavior
Scripts currently have write access to the `/piston/jobs` directory and these writes are not tracked by the job scheduler. This means a script can create a folder in this directory and store information there, which can then be later read by other instances of the script.

## Possible Solution
Configuring sandbox file permissions to only allow scripts to read their own directory is ideal, but a possible workaround would be on script completion to clean up the `/piston/jobs` directory by creation user ID instead of only the UUID folder.

## Steps to Reproduce
1. Running this shell will create a random `foo` directory and set its permissions to be universally read-write-executable, allowing any users on the same instance to load and modify data in it. It will also add a sample script in `foo-{N}/script` that will echo `yeehaw` when run.
```sh
mydir=../foo-$RANDOM
mkdir $mydir
echo -e '#!/bin/sh\necho yeehaw' > $mydir/script
chmod -R 777 $mydir
echo $mydir
```
2. This bash will run the script generated by the above (with the directory configured correctly).
```sh
mydir=../foo-23903
$mydir/script
touch $mydir/foo
ls $mydir
```

## Context (Environment)
This issue was found while examining directory permissions in the [Felix](https://github.com/engineer-man/felix) Discord bot. I'm not certain whether this issue belongs here or there, but since it's related to Piston's sandboxing I put it here.

**Comment by josephreed2600** [comment]
Could this be fixed by having the scheduler create the working directory, then changing its owner to the running user, so that executors don't need write access to /piston/jobs/ to create their directories?

**Comment by HexF** [comment]
> Could this be fixed by having the scheduler create the working directory, then changing its owner to the running user, so that executors don't need write access to /piston/jobs/ to create their directories?
Thats how its ment to work.
It seems like the permissions of `/piston/jobs/` have been messed up, I'll put a fix in right away.
