### ISSUE TITLE
How can you make piston serve from a https url for an nginx server?

### ISSUE THREAD

**Issue by clarodanesh** [engineer-man/piston#491]
Piston currently runs at http://test.example.com:2000 but when I try to serve it from https://test.example.com:2000 I get an ssl cert error. This means I cannot make fetch requests to the api as I am sending the fetch request from a https context.

Any help would be appreciated thank you.

**Comment by HexF** [comment]
You should setup an [NGINX reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) or another type of reverse proxy to forward requests to piston, which can terminate the SSL for you.

**Comment by clarodanesh** [comment]
Thank you very much I have managed to do this now, just another resource I used with the one above for anyone who finds this helpful [Add headers resource](https://serverfault.com/a/901006)

```
location / {
            #if ($request_method = 'POST') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            #}
            proxy_pass http://127.0.0.1:2000;
            proxy_set_header Host      $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
}
```

I added this to my first server block in my nginx config file
