### ISSUE TITLE
can't open file [Permission Denied] error message

### ISSUE THREAD

**Issue by gouseferoz** [engineer-man/piston#492]
Hi, While using the API, i am seeing following message as the output:

python3.10: can't open file '/piston/jobs/f7001ee7-8d17-4e97-8ff9-1db5bc1db945/test.py': [Errno 13] Permission denied\n","code":2,"signal":null,"output":"python3.10: can't open file '/piston/jobs/f7001ee7-8d17-4e97-8ff9-1db5bc1db945/test.py

How can i fix this?

Thanks

**Comment by serithemage** [comment]
I'm having the same problem.
The following are the commands I have executed.

``` bash
# clone and enter repo
git clone https://github.com/engineer-man/piston
cd piston

# Start the API container
docker-compose up -d api

# Install all the dependencies for the cli
cd cli && npm i && cd -

# Install latest python
cli/index.js ppman install python

# Run a python script using the latest version
echo 'print("Hello world!")' > test.py
cli/index.js run python test.py
```

**Comment by arduano** [comment]
Adding `privileged: true` to docker-compose.yaml fixed it for me personally

**Comment by Brikaa** [comment]
Restarting piston (`./piston restart`) fixes it. I am assuming it has to do with the fact that the jobs directory is created after the node process starts in the first run

**Comment by gouseferoz** [comment]
Thanks @arduano  and @Brikaa I will try these and will update.
