### ISSUE TITLE
Unable to install package for any language - High PRI - Github package link is broken

### ISSUE THREAD

**Issue by jayasurya-jeyakodi** [engineer-man/piston#515]
Unable to add any language with the following command
`cli/index.js ppman install python`

I am getting the below error

<img width="474" alt="image" src="https://user-images.githubusercontent.com/61740177/190097788-0323ef41-b033-415f-bb5d-29c4ec1b8923.png">

Digging through the code I found that it's trying to source packages from [https://github.com/engineer-man/piston/releases/download/pkgs/index](url) but looks like this link is broken, I am not if this is the reason though.

Can you please suggestion why this isn't working?

**Comment by Kogs** [comment]
We have the same problem. No Packages can get installed.

**Comment by HexF** [comment]
see #516
