### ISSUE TITLE
Not able to install packages

### ISSUE THREAD

**Issue by boopeshmahendran227** [engineer-man/piston#516]
When we run `cli/index.js ppman install python`, it throws an error `requested package not found`

We then debugged the code and found that package list is fetched from this url - `https://github.com/engineer-man/piston/releases/download/pkgs/index`

This url returns 404 currently

**Comment by Kogs** [comment]
Same here, please fix.

**Comment by HexF** [comment]
Should be fixed now, some reason the index didn't build when a new package was merged.

**Comment by Kogs** [comment]
It works now, thanks a lot my man :) 👍

**Comment by jayasurya-jeyakodi** [comment]
@Kogs Did you clear some cache? the issue still exists for me

**Comment by jayasurya-jeyakodi** [comment]
thanks, redeploying worked
