### ISSUE TITLE
No response when running certain programs

### ISSUE THREAD

**Issue by brtwrst** [engineer-man/piston#52]
Programs like:

bash
```
yes
```
and 

cpp
```
#include <iostream>

int main()
{
    while (true)
    {
        &printf == 0x000;
        printf("test");
    }
}
```

cause the API to "hang" and not send any reply.

**Comment by Vrganj** [comment]
It could possibly be caused by the output not being limited

**Comment by Vrganj** [comment]
Actually, Node might have ran out of memory. It'd probably be a better idea to use `head` in Bash to trim it
