### ISSUE TITLE
Migrate api codebase to typescript

### ISSUE THREAD

**Issue by CaedenPH** [engineer-man/piston#520]
Migrate the api codebase from javascript to typescript. I think migrating the project to typescript will significantly improve the development experience since it allows us to catch errors earlier.

**Comment by Brikaa** [comment]
I don't think TypeScript will offer us a good advantage since the project revolves around optimizing the execution and cleaning up of child processes rather than applying software engineering concepts. 

I think if we were to change languages, we would pick one that helps us achieve this objective.

**Comment by HexF** [comment]
I was considering rust for a while, but at this moment in time I don't see any reason simply because it works already.
