### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by LoryPelli** [engineer-man/piston#545]
Can somebody help me pls?
I'm using this
```js
for (let i = 0; i < runtimes.length; i++) {
    for (let c = 0; c < runtimes[i].aliases.length; c++) {
        if (language.toLowerCase() == runtimes[i].language || language.toLowerCase() == runtimes[i].aliases[c]) {
            language = runtimes[i].language
            version = runtimes[i].version
        }
    }
}
```
to check if the input language is supported by piston but it doesn't appear to be working with `Java`, why?

**Comment by realtux** [comment]
this appears to be a request for code help, please do so on discord https://discord.gg/engineerman. if there's an actual issue with piston, please let us know.

**Comment by LoryPelli** [comment]
> this appears to be a request for code help, please do so on discord https://discord.gg/engineerman. if there's an actual issue with piston, please let us know.

I did this on the piston channel

**Comment by LoryPelli** [comment]
![image](https://user-images.githubusercontent.com/87276663/222516784-6d2bf8eb-faf5-49c6-b883-e31e774b6364.png)
@realtux
