### ISSUE TITLE
Not all errors are returned.

### ISSUE THREAD

**Issue by MarketingPip** [engineer-man/piston#547]
Not all errors are not thrown. Some language have errors returned in API other's do NOT.

**Comment by Jonxslays** [comment]
Can you provide a more specific example?

What language are you using, what code are you running, what error do you expect to get thrown, what actually happens when you run the code with piston?

**Comment by MarketingPip** [comment]
Sorry for not touching base on this!

I couldn't investigate what really happened when this error occurred (maybe it was something my side but 🤷‍♂️)

It appears nothing has happened similar tho.

Tho I'll report if anything strange happens with latest API updates.✌️
