### ISSUE TITLE
Third Party Libraries Support

### ISSUE THREAD

**Issue by sriramr98** [engineer-man/piston#553]
How can we include a third party library with the execution of any code? For example, I want to use https://github.com/stleary/JSON-java with a Java snippet to execute. Is there a way to do this currently? As far as the documentation goes, I don't see any, but if this is useful [ which it is to me ], I will submit a PR for a feature.

**Comment by HexF** [comment]
On public piston there won't be support for additional libraries for a while - this is on the roadmap for a later revision.
You could modify the java package on your own instance to install this library if you wish.

**Comment by adityasahas** [comment]
> On public piston there won't be support for additional libraries for a while - this is on the roadmap for a later revision. You could modify the java package on your own instance to install this library if you wish.

How could we do this?
