### ISSUE TITLE
Strange js issue

### ISSUE THREAD

**Issue by LoryPelli** [engineer-man/piston#554]
![image](https://user-images.githubusercontent.com/87276663/227989621-5b008f2b-6bd8-4e24-916e-934be531df2b.png)
I'm not sure why this is happening (also with official piston bot)

**Comment by LoryPelli** [comment]
/piston/jobs/efe5a217-d581-46cf-80b5-aa207a33b336/file0.code:8
    return `​${giorniPassati} giorni fa`​;
                                        

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

**Comment by realtux** [comment]
please use code blocks. some characters are being removed.

**Comment by LoryPelli** [comment]
> please edit to use code blocks. some characters are being removed.

Done

**Comment by realtux** [comment]
this isn't a piston issue. you have some invisible unicode character before the dollar signs. try this code instead and see below
```js
function calcolaTempo(data) {
    const dataIniziale = new Date(data);
    const oggi = new Date();
    const differenza = oggi.getTime() - dataIniziale.getTime();

    if (differenza > 0) {
        const giorniPassati = Math.floor(differenza / (1000 * 60 * 60 * 24));
        return `${giorniPassati} giorni fa`;
    } else if (differenza < 0) {
        const giorniMancanti = Math.ceil(Math.abs(differenza) / (1000 * 60 * 60 * 24));
        return `${giorniMancanti} giorni mancanti`;
    } else {
        return "Oggi è il giorno specificato!";
    }
}

const data = "1/1/2022";
console.log(calcolaTempo(data));
```

![image](https://user-images.githubusercontent.com/4989650/227993983-f1214fc8-2736-4edc-b289-9153c7a67855.png)

**Comment by LoryPelli** [comment]
> this isn't a piston issue. you have some invisible unicode character before the dollar signs. try this code instead and see below
> 
> ```js
> function calcolaTempo(data) {
>     const dataIniziale = new Date(data);
>     const oggi = new Date();
>     const differenza = oggi.getTime() - dataIniziale.getTime();
> 
>     if (differenza > 0) {
>         const giorniPassati = Math.floor(differenza / (1000 * 60 * 60 * 24));
>         return `${giorniPassati} giorni fa`;
>     } else if (differenza < 0) {
>         const giorniMancanti = Math.ceil(Math.abs(differenza) / (1000 * 60 * 60 * 24));
>         return `${giorniMancanti} giorni mancanti`;
>     } else {
>         return "Oggi è il giorno specificato!";
>     }
> }
> 
> const data = "1/1/2022";
> console.log(calcolaTempo(data));
> ```
> 
> ![image](https://user-images.githubusercontent.com/4989650/227993983-f1214fc8-2736-4edc-b289-9153c7a67855.png)

That character should be also in your bot (it's used to avoid codeblock escape)

**Comment by realtux** [comment]
unicode u+200b is zero width space. i'm not sure what that has to do with codeblock escapes. there is no bot issue or piston issue. if i just run your code from a file and don't even use piston or piston-bot, it's the same outcome:
![image](https://user-images.githubusercontent.com/4989650/227995856-065ac349-5452-473c-a0a5-6263a3e33b2d.png)

**Comment by LoryPelli** [comment]
> this is only for the output though. the input code is not transformed at all. i don't really know how those characters got into the input code. i just copy and pasted the code you sent me for testing and it had the characters already in it.

Yes, I was using a global regex to replace every character in the input code
