### ISSUE TITLE
Languages Version

### ISSUE THREAD

**Issue by LoryPelli** [engineer-man/piston#556]
Why some languages use an outdated version (for example nodejs 16)?

**Comment by HexF** [comment]
These need to be manually updated in the piston repo, and haven't been touched in a while. 
You are more than welcome to submit pull-requests updating packages to the latest versions.

**Comment by LoryPelli** [comment]
> These need to be manually updated in the piston repo, and haven't been touched in a while. 
> You are more than welcome to submit pull-requests updating packages to the latest versions.

Does i need to edit only metadata.json file for nodejs?
