### ISSUE TITLE
Node 18.15.0

### ISSUE THREAD

**Issue by LoryPelli** [engineer-man/piston#559]
My pull request was merged but piston language version continues to be 16.3.0 in runtimes, why?

**Comment by LoryPelli** [comment]
Here is the link
https://github.com/engineer-man/piston/pull/557

**Comment by HexF** [comment]
Are you referring to public piston? If so, I need to install the new package on the public instance before it will be available there.

**Comment by LoryPelli** [comment]
> Are you referring to public piston? If so, I need to install the new package on the public instance before it will be available there.

Yes, please do it

**Comment by LoryPelli** [comment]
@HexF any updates?
