### ISSUE TITLE
Deno issue

### ISSUE THREAD

**Issue by lorypelli** [engineer-man/piston#560]
![image](https://user-images.githubusercontent.com/87276663/230181796-0baf58de-7e73-47f6-b2f0-c0fbc808d521.png)
as you can see there are strange question marks and others strange things...why?
is this related to this pull request? https://github.com/engineer-man/piston/commit/32012483a30667e96296b14b5b9829715d0ef2a6

**Comment by HexF** [comment]
Yes, I imagine I will need to reinstall the deno package on public piston to get that resolved
