### ISSUE TITLE
Preserve newlines in stdin

### ISSUE THREAD

**Issue by Vrganj** [engineer-man/piston#57]
Stdin is passed as argv, which is probably why it turns newlines into spaces. To get around this, the stdin file should be written to directly, the same way the code is.

By the way, why does the API write to a temporary file and let the executor copy it instead of just writing to the final path? Is there a reason for that? I just copied what the previous API did when rewriting it.

**Comment by Vrganj** [comment]
My idea for a fix is writing to the final paths and passing the epoch to the execute script.

**Comment by realtux** [comment]
it does this because the cli takes language and source file as input and the api is just a wrapper around the cli

**Comment by Vrganj** [comment]
Ah, I always forget about the cli

**Comment by realtux** [comment]
there's nothing that says the api can't write it directly to lxc though, you'd just have to modify the cli to take just language and epoch in addition to functioning the same way it currently does

**Comment by Vrganj** [comment]
Yeah, that was the idea I mentioned, I guess I'll do that
