### ISSUE TITLE
[Feature Request] OpenAI plugin

### ISSUE THREAD

**Issue by nitanmarcel** [engineer-man/piston#634]
Could we get have an OpenAI plugin implementation for piston? This would bring piston code execution in gpt allowing to sandbox-ly execute code that gets sent to us, and to execute code that we send.

With librechat, we would also gave the possibility to host our own instance and have the plugin working there for a whole organization, or in my case, a group of friends directly with the help with openai api

https://platform.openai.com/docs/plugins/getting-started

**Comment by HexF** [comment]
From my understanding of your request, this is implementing a "Run with Piston" on any code-blocks OpenAI's models may generate. 
To that extent, this feel out-of-scope for piston and as such am closing the issue.
This would be best as another project which simply calls upon the Piston API to run OpenAI produced code.

**Comment by nitanmarcel** [comment]
> From my understanding of your request, this is implementing a "Run with Piston" on any code-blocks OpenAI's models may generate. To that extent, this feel out-of-scope for piston and as such am closing the issue. This would be best as another project which simply calls upon the Piston API to run OpenAI produced code.

It's actually just an manifest and an openapi specification laying in the server and gpt does the rest such as sending and receiving the data from the server.

https://github.com/pluralsight/chatgpt-plugin-demo

**Comment by nitanmarcel** [comment]
> From my understanding of your request, this is implementing a "Run with Piston" on any code-blocks OpenAI's models may generate. To that extent, this feel out-of-scope for piston and as such am closing the issue. This would be best as another project which simply calls upon the Piston API to run OpenAI produced code.

From my understanding is actually just an json metadata (ai-plugin.json) at the `/.well-known/ai-plugin.json` and an openapi specification in the root path and gpt handles and parses the request itself.

https://github.com/pluralsight/chatgpt-plugin-demo/tree/master
