### ISSUE TITLE
Can I use Piston for running tests?

### ISSUE THREAD

**Issue by materemias** [engineer-man/piston#636]
Would it be possible to upload a source file and a test file to piston and execute the tests on the source? 

In a simple setup it could be something like a ts file and an associated jest test, can it be done by defining a new package and adding jest to it? Do you see any complications that may arise from that?

On a more complex level, I would try to do the same with Java/kotlin and Junit/kotest.

Thanks in advance!

**Comment by HexF** [comment]
Yes it would - you can run any sort of code on Piston, including testing frameworks.
