### ISSUE TITLE
Update C++ Standard to C++20

### ISSUE THREAD

**Issue by Chronophylos** [engineer-man/piston#65]
Since the C++20 standard has been published in December 2020 piston should use it.

This could be as easy as changing `-std=c++17` to `-std++20` in https://github.com/engineer-man/piston/blob/0f8350b6da6786ae140e79806e1ff92d1047f3bd/lxc/executors/cpp#L4
but I'm not sure if the installed `g++` compiler supports C++20

**Comment by Vrganj** [comment]
Just checked, GCC needs to be updated in order to do this

**Comment by realtux** [comment]
im going to assume this is solved in v3 since gcc is compiled from scratch and will likely be the latest version
