### ISSUE TITLE
Issue with self hosted python version OpenBLAS 

### ISSUE THREAD

**Issue by raeudigerRaeffi** [engineer-man/piston#662]
I am hosting a version of piston primarily for python code execution however most of the code we need to run quickly runs into limits with OpenBLAS. Is there any way how we can fix this issue.
Below is an example of an error code we get.

OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 32: Resource temporarily unavailable\nOpenBLAS blas_thread_init: RLIMIT_NPROC 
64 current, 64 max\nTraceback (most recent call last):\n  File "/piston/jobs/1fa09d00-c500-42d0-83de-3466cee0498b/main.py", line 7, in <module>\n    from sklearn.preprocessing import PolynomialFeatur
es\n  File "/piston/packages/python/3.12.0/lib/python3.12/site-packages/sklearn/__init__.py", line 87, in <module>\n    from .base import clone\n  File "/piston/packages/python/3.12.0/lib/python3.12/
site-packages/sklearn/base.py", line 19, in <module>\n    from .utils import _IS_32BIT\n  File "/piston/packages/python/3.12.0/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 16, in <mo
dule>\n    from scipy.sparse import issparse\n  File "/piston/packages/python/3.12.0/lib/python3.12/site-packages/scipy/sparse/__init__.py", line 287, in <module>\n    from . import csgraph\n', 'stdo
ut_bytes': '', 'stderr_bytes': 'OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 32: Resource temporarily unavailable\nOpenBLAS blas_thread_init: RLIMIT_NPROC 64 current,

**Comment by Brikaa** [comment]
Seems like you need to increase the maximum number of processes limit. Add this environment variable to the configuration of whatever you use to run Piston:
```
PISTON_MAX_PROCESS_COUNT=<number greater than 64>
```
If you are using the docker-compose file (via ./piston script for example), add it under an `environment:` key.
