### ISSUE TITLE
Suggestions for more languages

### ISSUE THREAD

**Issue by Chronophylos** [engineer-man/piston#68]
* [F#](https://fsharp.org/)
* [CoffeScript](https://coffeescript.org/)
* [Rockstar](https://github.com/RockstarLang/rockstar)
* Turbo Pascal and other Pascal Dialects with [Free Pascal](https://freepascal.org/) or [Modern Pascal](http://modernpascal.com/)

I have no clue who would use these, I just think it's fun to add more languages

**Comment by realtux** [comment]
for sure, the more the better

**Comment by ezNNP** [comment]
Turbo pascal would be nice

**Comment by Chronophylos** [comment]
I'm interested in adding languages but I am waiting for a more streamlined installation of piston.

**Comment by charles-allen** [comment]
To avoid repeat suggestions, here's those merged with the already supported list (I added Clojure, Erlang, Scala):
- [x] awk
- [x] bash
- [x] brainfuck
- [x] c
- [ ] [clojure](https://clojure.org)
- [ ] [coffeescript](https://coffeescript.org)
- [x] cpp
- [x] crystal
- [x] csharp
- [x] d
- [x] dash
- [x] deno
- [x] elixir
- [x] emacs
- [x] elisp
- [ ] [erlang](https://www.erlang.org)
- [ ] [fsharp](https://fsharp.org)
- [x] go
- [x] haskell
- [x] java
- [x] jelly
- [x] julia
- [x] kotlin
- [x] lisp
- [x] lua
- [x] nasm
- [x] nasm64
- [x] nim
- [x] node
- [x] osabie
- [x] paradoc
- [ ] pascal ([free pascal](https://freepascal.org) or [modern pascal](http://modernpascal.com))
- [x] perl
- [x] php
- [x] python2
- [x] python3
- [ ] [rockstar](https://github.com/RockstarLang/rockstar)
- [x] ruby
- [x] rust
- [ ] [scala](https://www.scala-lang.org)
- [x] swift
- [x] typescript
- [x] zig

**Comment by Vrganj** [comment]
It seems that elixir install includes erlang

**Comment by LewisScript** [comment]
I think COW would be great

**Comment by Shivansh-007** [comment]
- [ ] [Groovy](https://groovy-lang.org/)
- [ ] [OCaml](https://ocaml.org/)
- [ ] [Pony](https://www.ponylang.io/)
- [ ] [Rill](https://github.com/yutopp/rill)
- [ ] Vim Script

**Comment by charles-allen** [comment]
Is the list of [supported languages](https://github.com/engineer-man/piston#supported-languages) in the README out-of-date? It seems several are checked off here that aren't listed there.

**Comment by realtux** [comment]
they are implemented in v3 which should be releasing in the next few weeks

**Comment by Shivansh-007** [comment]
> Is the list of [supported languages](https://github.com/engineer-man/piston#supported-languages) in the README out-of-date?
> It seems several are checked off here that aren't listed there.

Yes @charles-allen, the list seems to be out of date, and as you are the author of the list, it would be good If you update them according to the `v3` version, you can see `packages/` folder inside `v3` branch.

**Comment by charles-allen** [comment]
> Looks like you already did it, thanks!

I merged the new langs & checked off Scala based on the readme. Actually someone else is keeping my post up-to-date with the v3 branch (I didn't realise it was branched).

**Comment by ve4k** [comment]
POSIX sh and Kotlin

**Comment by brainplot** [comment]
If piston is hosted on an Ubuntu box, POSIX sh should be easy to implement as Ubuntu already comes with `dash`.

**Comment by ve4k** [comment]
> If piston is hosted on an Ubuntu box, POSIX sh should be easy to implement as Ubuntu already comes with `dash`.

Or just use /bin/sh which is 100% POSIX compliant and included on >all< linux machines

**Comment by brainplot** [comment]
> > If piston is hosted on an Ubuntu box, POSIX sh should be easy to implement as Ubuntu already comes with `dash`.
> 
> Or just use /bin/sh which is 100% POSIX compliant and included on >all< linux machines

That's correct but it may not be what you want, depending on what you mean by "POSIX sh". Many distros have `/bin/sh` symlinked to Bash, which is a POSIX compliant but not a *strictly* POSIX compliant shell. That is, it adds (many) features on top of the POSIX standard. `dash` on the other hand only supports the subset of features POSIX mandates a POSIX-compliant shell to support.

The way I see it, it'd be a good idea to add a strictly POSIX shell to Piston as it would help answer questions of the likes of "Is this bashism or can I use it in other shells too?".

**Comment by Vrganj** [comment]
Piston already supports `dash`

**Comment by HexF** [comment]
Any remaining language suggestions should be split into their own issues and will be implemented on a per-issue basis
