### ISSUE TITLE
In socket mode, python outputs come delayed and not immediate

### ISSUE THREAD

**Issue by RahulBadenkal** [engineer-man/piston#682]
When i execute the below python program in socket mode (via `/connect)`

```
from time import sleep

sleep(3)
print('1')

sleep(3)
print('2')

sleep(3)
print('3')
```

The output all comes at once, rather than at 3 sec intervals

**Comment by RahulBadenkal** [comment]
Looks like adding this env variable `PYTHONUNBUFFERED = 1`  makes stdout/stdin streams to be unbuffered. [Reference](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED)


Adding `-u` flag to request doesn't work as we need `-u <file-name>` but in the api app the args are set the other way `<file-name ...flags>` [Reference](https://github.com/engineer-man/piston/blob/59338eee333606af6b7e5aa459ce63b6a3da2757/api/src/job.js#L338
)

Possible to add `PYTHONUNBUFFERED = 1` to the package env file of python?
https://github.com/engineer-man/piston/blob/master/packages/python/3.12.0/environment

**Comment by Brikaa** [comment]
For now, you can use `print('1', flush=True)`. I think this should cause the output to appear immediately.

**Comment by RahulBadenkal** [comment]
While what you mentioned works, it would be better if it was added as part of the env file so the user won't have be informed to set flush while executing code.

For now I have forked the repo and added a post build script that installs python package and updates the env file.
