### ISSUE TITLE
Ability to install PIP packages for Python code execution

### ISSUE THREAD

**Issue by praveenprem** [engineer-man/piston#76]
Most of the time users want a sandbox environment to test how a function from a package works; it would be very useful to have an option to provide a list of packages that should be installed on the container before code execution.

Something like this would be my suggestion to keep backward compatibility:

```json
{
    "language": "python",
    "source": "import bcrypt\npassword = b\"super secret password\"\nhashed = bcrypt.hashpw(password, bcrypt.gensalt())\nif bcrypt.checkpw(password, hashed):\n    print('It Matches!')\nelse:\n    print('It Does not Match :(')",
    "stdin": "",
    "args": [
    ],
    "packages": [
        "bcrypt"
    ]
}
```

**Comment by realtux** [comment]
pip install of custom packages at execution time won't happen. i am open to installing a certain set of core packages that are really popular.

**Comment by HexF** [comment]
#133 covers this
