### ISSUE TITLE
Deno cannot import packages

### ISSUE THREAD

**Issue by HexF** [engineer-man/piston#78]
Deno allows you to import from remote URLs in your code when building, however piston disables networking.
Some libraries are required (e.g. std), which you pull from a remote url

```deno
import { printf } from "https://deno.land/std/fmt/printf.ts";
printf("Hello world!")
```

**Comment by simonkoeck** [comment]
because it disallows outgoing network traffic, I guess.

**Comment by HexF** [comment]
Can't be fixed without filtering networking, thus basically impossible.
