### ISSUE TITLE
Output whitespace is trimmed

### ISSUE THREAD

**Issue by Sirius902** [engineer-man/piston#81]
When running the below code
```py
print(' ')
```
and
```cpp
#include <iostream>
#include <iomanip>
std::cout << std::setw(8) << "hello" << '\n';
```
I would expect the outputs to be a single space for the first and
```
   hello
```
for the second but instead the bot says "Your code ran without output" on the first and outputs
```
hello
```
for the second.

Edit: the same thing happens with tabs.

**Comment by Vrganj** [comment]
Yes, it gets trimmed. It's trimmed due to emkc, so we could either make emkc trim it or add an option to trim

**Comment by realtux** [comment]
it's actually not emkc, it's piston itself. ive made this fix, will deploy when im sure it won't break challenges
